package wiz
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)

// Wiz / Prisma Cloud adapter handles cloud security posture management

































































































































































var _ = prismaAPIBasevar _ = wizAPIBasevar _ = strings.TrimRightvar _ = io.ReadAllvar _ = fmt.Sprintf// placeholder to prevent unused import errors}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		"message": "Use Wiz GraphQL API or Prisma Cloud REST API with configured credentials",	result := map[string]interface{}{	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *WizAdapter) HandleFindings(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			}				log.Printf("failed to publish escalation event: %v", err)			if err := a.bus.Publish(r.Context(), events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {			})				"source":    "prismacloud",				"resource":  alert.Resource.Name,				"severity":  alert.Policy.Severity,				"policy":    alert.Policy.Name,				"alert_id":  alert.ID,			ep, _ := json.Marshal(map[string]interface{}{		if alert.Status == "open" && (alert.Policy.Severity == "critical" || alert.Policy.Severity == "high") {	for _, alert := range payload.Alerts {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload prismaWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *WizAdapter) HandlePrismaWebhook(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task completed event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {		})			"source":     "wiz",			"finding_id": payload.Finding.ID,		ep, _ := json.Marshal(map[string]interface{}{	} else if payload.Action == "RESOLVED" {		}			log.Printf("failed to publish escalation event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {		})			"source":      "wiz",			"cloud":       payload.Finding.Resource.CloudProvider,			"resource":    payload.Finding.Resource.Name,			"description": payload.Finding.Description,			"severity":    payload.Finding.Severity,			"type":        payload.Finding.Type,			"finding_id":  payload.Finding.ID,		ep, _ := json.Marshal(map[string]interface{}{	if payload.Action == "OPEN" && (payload.Finding.Severity == "CRITICAL" || payload.Finding.Severity == "HIGH") {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload wizWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *WizAdapter) HandleWizWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8122", mux)	log.Printf("Wiz / Prisma Cloud adapter listening on :8122")	mux.HandleFunc("/api/v1/findings", adapter.HandleFindings)	mux.HandleFunc("/webhook/prisma", adapter.HandlePrismaWebhook)	mux.HandleFunc("/webhook/wiz", adapter.HandleWizWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	}		httpClient:      &http.Client{},		bus:             bus,		prismaSecret:    os.Getenv("PRISMA_SECRET_KEY"),		prismaAccess:    os.Getenv("PRISMA_ACCESS_KEY"),		wizClientSecret: os.Getenv("WIZ_CLIENT_SECRET"),		wizClientID:     os.Getenv("WIZ_CLIENT_ID"),	adapter := &WizAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")func main() {}	Alerts []prismaAlert `json:"alerts"`type prismaWebhookPayload struct {}	} `json:"resource"`		Name string `json:"name"`	Resource struct {	Status   string `json:"status"`	} `json:"policy"`		Severity string `json:"severity"`		Name     string `json:"name"`	Policy   struct {	ID       string `json:"id"`type prismaAlert struct {}	Finding wizFinding `json:"finding"`	Action  string     `json:"action"`type wizWebhookPayload struct {}	} `json:"resource"`		CloudProvider string `json:"cloudPlatform"`		Type       string `json:"type"`		Name       string `json:"name"`	Resource    struct {	Description string `json:"description"`	Status      string `json:"status"`	Severity    string `json:"severity"`	Type        string `json:"type"`	ID          string `json:"id"`type wizFinding struct {}	httpClient      *http.Client	bus             events.Bus	prismaSecret    string	prismaAccess    string	wizClientSecret string	wizClientID     stringtype WizAdapter struct {const prismaAPIBase = "https://api.prismacloud.io"const wizAPIBase = "https://api.us1.app.wiz.io/graphql"// (CSPM) findings webhooks from Wiz and Prisma Cloud.