package vault
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"








































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("vault API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	}		req.Header.Set("X-Vault-Namespace", a.namespace)	if a.namespace != "" {	req.Header.Set("X-Vault-Token", a.token)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, a.baseURL+vaultAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *VaultAdapter) vaultRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.TaskCreated}, func(e events.Event) error {	ctx := context.Background()func (a *VaultAdapter) subscribeToEvents() {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.vaultRequest(r.Context(), http.MethodPut, "/sys/leases/revoke", req, &result); err != nil {	var result map[string]interface{}	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req map[string]interface{}	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPut {func (a *VaultAdapter) HandleLeaseRevoke(w http.ResponseWriter, r *http.Request) {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.vaultRequest(r.Context(), http.MethodPut, "/sys/leases/renew", req, &result); err != nil {	var result map[string]interface{}	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req map[string]interface{}	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPut {func (a *VaultAdapter) HandleLeaseRenew(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.vaultRequest(r.Context(), http.MethodGet, "/secret/data/"+path, nil, &result); err != nil {		var result map[string]interface{}	case http.MethodGet:	switch r.Method {	}		return		http.Error(w, "path query parameter is required", http.StatusBadRequest)	if path == "" {	path := r.URL.Query().Get("path")func (a *VaultAdapter) HandleSecrets(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish escalation event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {		})			"source":     "vault",			"error":      log_.Error,			"path":       log_.Request.Path,			"operation":  log_.Request.Operation,			"request_id": log_.Request.ID,		ep, _ := json.Marshal(map[string]interface{}{	if log_.Error != "" {	// Surface denied operations as escalations	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&log_); err != nil {	var log_ vaultAuditLog	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *VaultAdapter) HandleAuditWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8121", mux)	log.Printf("HashiCorp Vault adapter listening on :8121")	mux.HandleFunc("/api/v1/lease/revoke", adapter.HandleLeaseRevoke)	mux.HandleFunc("/api/v1/lease/renew", adapter.HandleLeaseRenew)	mux.HandleFunc("/api/v1/secrets", adapter.HandleSecrets)	mux.HandleFunc("/webhook/audit", adapter.HandleAuditWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient: &http.Client{},		bus:        bus,		namespace:  os.Getenv("VAULT_NAMESPACE"),		token:      token,		baseURL:    strings.TrimRight(baseURL, "/"),	adapter := &VaultAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("VAULT_ADDR and VAULT_TOKEN are required")	if baseURL == "" || token == "" {	token := os.Getenv("VAULT_TOKEN")	baseURL := os.Getenv("VAULT_ADDR")func main() {}	Error string `json:"error"`	} `json:"request"`		Path      string `json:"path"`		Operation string `json:"operation"`		ID        string `json:"id"`	Request struct {	} `json:"auth"`		DisplayName string `json:"display_name"`		Policies    []string `json:"policies"`		Accessor    string `json:"accessor"`		ClientToken string `json:"client_token"`	Auth    struct {	Time    string `json:"time"`	Type    string `json:"type"`type vaultAuditLog struct {}	httpClient *http.Client	bus        events.Bus	namespace  string	token      string	baseURL    stringtype VaultAdapter struct {const vaultAPIBase = "/v1")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"