package pagerduty
package main

import (
	"bytes"
	"context"
	"encoding/json"



















































































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("pagerduty API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	}		req.Header.Set("From", a.fromEmail)	if a.fromEmail != "" {	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Accept", "application/vnd.pagerduty+json;version=2")	req.Header.Set("Authorization", "Token token="+a.apiKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, pagerDutyAPIBase+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *PagerDutyAdapter) pdRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// pdRequest is a helper that executes an authenticated PagerDuty REST API call.}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.pdRequest(r.Context(), http.MethodPut, "/incidents/"+incidentID, req, &result); err != nil {		var result map[string]interface{}		req.Incident.Type = "incident"		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req pdUpdateIncidentRequest		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if incidentID == "" {		incidentID := r.URL.Query().Get("id")	case http.MethodPut:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.pdRequest(r.Context(), http.MethodPost, "/incidents", req, &result); err != nil {		var result map[string]interface{}		}			req.Incident.Service = pdRef{ID: a.serviceID, Type: "service_reference"}		if req.Incident.Service.ID == "" {		req.Incident.Type = "incident"		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req pdCreateIncidentRequest	case http.MethodPost:	switch r.Method {func (a *PagerDutyAdapter) HandleIncidents(w http.ResponseWriter, r *http.Request) {// HandleIncidents exposes a REST endpoint so other services can create/resolve incidents.}	return a.pdRequest(context.Background(), http.MethodPost, "/incidents", req, nil)	}		},			},				Details: payload.Reason,				Type:    "incident_body",			Body: &pdBody{			Urgency: "high",			Service: pdRef{ID: a.serviceID, Type: "service_reference"},			Title:   title,			Type:    "incident",		Incident: pdNewIncident{	req := pdCreateIncidentRequest{	}		title = fmt.Sprintf("Forge: %s — %s", payload.JiraKey, payload.Reason)	if payload.JiraKey != "" {	title := fmt.Sprintf("Forge: task %s failed", payload.TaskID)	}		return nil	if payload.Source == "pagerduty" {	// Skip incidents that originated from PagerDuty to avoid loops.	json.Unmarshal(e.Payload, &payload)	}		Source  string `json:"source"`		Reason  string `json:"reason"`		JiraKey string `json:"jira_key"`		TaskID  string `json:"task_id"`	var payload struct {func (a *PagerDutyAdapter) createIncident(e events.Event) error {}	})		return nil		}			return a.createIncident(e)		case events.TaskFailed:			return a.createIncident(e)		case events.EscalationCreated:		switch e.Type {	}, func(e events.Event) error {		events.TaskFailed,		events.EscalationCreated,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *PagerDutyAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge events and creates/resolves PagerDuty incidents.}	log.Printf("PagerDuty incident acknowledged: %s (%s)", inc.ID, inc.Title)func (a *PagerDutyAdapter) handleIncidentAcknowledged(ctx context.Context, inc pdIncident) {}	}		log.Printf("failed to publish task completed event: %v", err)	}); err != nil {		Payload: payload,		Type:    events.TaskCompleted,	if err := a.bus.Publish(ctx, events.Event{	})		"source":      "pagerduty",		"title":       inc.Title,		"incident_id": inc.ID,	payload, _ := json.Marshal(map[string]interface{}{func (a *PagerDutyAdapter) handleIncidentResolved(ctx context.Context, inc pdIncident) {}	}		log.Printf("failed to publish escalation event: %v", err)	}); err != nil {		Payload: payload,		Type:    events.EscalationCreated,	if err := a.bus.Publish(ctx, events.Event{	})		"source":      "pagerduty",		"url":         inc.HTMLURL,		"urgency":     inc.Urgency,		"title":       inc.Title,		"incident_id": inc.ID,	payload, _ := json.Marshal(map[string]interface{}{func (a *PagerDutyAdapter) handleIncidentTriggered(ctx context.Context, inc pdIncident) {}	w.WriteHeader(http.StatusOK)	}		}			a.handleIncidentAcknowledged(r.Context(), msg.Incident)		case "incident.acknowledge":			a.handleIncidentResolved(r.Context(), msg.Incident)		case "incident.resolve":			a.handleIncidentTriggered(r.Context(), msg.Incident)		case "incident.trigger":		switch msg.Event {	for _, msg := range envelope.Messages {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&envelope); err != nil {	var envelope pdWebhookEnvelope	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *PagerDutyAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound PagerDuty webhook events.}	http.ListenAndServe(":8098", mux)	log.Printf("PagerDuty adapter listening on :8098")	mux.HandleFunc("/api/v1/incidents", adapter.HandleIncidents)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:        bus,		httpClient: &http.Client{},		fromEmail:  os.Getenv("PAGERDUTY_FROM_EMAIL"),		serviceID:  os.Getenv("PAGERDUTY_SERVICE_ID"),		apiKey:     apiKey,	adapter := &PagerDutyAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("PAGERDUTY_API_KEY is required")	if apiKey == "" {	apiKey := os.Getenv("PAGERDUTY_API_KEY")func main() {}	Resolution string `json:"resolution,omitempty"`	Status     string `json:"status"`	Type       string `json:"type"`type pdUpdateIncident struct {}	Incident pdUpdateIncident `json:"incident"`type pdUpdateIncidentRequest struct {}	Details string `json:"details"`	Type    string `json:"type"`type pdBody struct {}	Type string `json:"type"`	ID   string `json:"id"`type pdRef struct {}	Body    *pdBody   `json:"body,omitempty"`	Urgency string    `json:"urgency,omitempty"`	Service pdRef     `json:"service"`	Title   string    `json:"title"`	Type    string    `json:"type"`type pdNewIncident struct {}	Incident pdNewIncident `json:"incident"`type pdCreateIncidentRequest struct {// PagerDuty REST API request/response types}	ServiceID   string `json:"service_id"`	HTMLURL     string `json:"html_url"`	Urgency     string `json:"urgency"`	Status      string `json:"status"`	Title       string `json:"title"`	ID          string `json:"id"`type pdIncident struct {}	Incident pdIncident `json:"incident"`	Event   string    `json:"event"`type pdWebhookMessage struct {}	Messages []pdWebhookMessage `json:"messages"`type pdWebhookEnvelope struct {// PagerDuty webhook payload structures}	bus        events.Bus	httpClient *http.Client	fromEmail  string	serviceID  string	apiKey     stringtype PagerDutyAdapter struct {const pagerDutyAPIBase = "https://api.pagerduty.com")	"github.com/dotrage/forge-adp/pkg/events"	"os"	"net/http"	"log"	"io"	"fmt"