package snyk
package main

import (
	"bytes"
















































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("snyk API error %d: %s", resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "token "+a.apiToken)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, snykAPIBase+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *SnykAdapter) snykRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// snykRequest is a helper that executes an authenticated Snyk REST API call.}	})		return nil		// Future: trigger a Snyk test when a new task with security label is created.	}, func(e events.Event) error {		events.TaskCreated,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *SnykAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge events that should trigger Snyk actions.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	); err != nil {		&result,		nil,		fmt.Sprintf("/org/%s/projects", a.orgID),	if err := a.snykRequest(r.Context(), http.MethodGet,	var result snykProjectsResponse	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *SnykAdapter) HandleProjects(w http.ResponseWriter, r *http.Request) {// HandleProjects lists Snyk projects for the configured organisation.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	); err != nil {		&result,		map[string]interface{}{"includeDescription": false},		fmt.Sprintf("/org/%s/project/%s/aggregated-issues", a.orgID, projectID),	if err := a.snykRequest(r.Context(), http.MethodPost,	var result snykIssuesResponse	}		return		http.Error(w, "project_id query parameter is required", http.StatusBadRequest)	if projectID == "" {	projectID := r.URL.Query().Get("project_id")	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *SnykAdapter) HandleVulnerabilities(w http.ResponseWriter, r *http.Request) {// HandleVulnerabilities proxies vulnerability queries for a specific project to Snyk's API.}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish escalation event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.EscalationCreated,		if err := a.bus.Publish(r.Context(), events.Event{		})			"reason":      fmt.Sprintf("Snyk detected %d new critical/high vulnerabilities in %s", len(criticalIssues), payload.Project.Name),			"issue_count": len(criticalIssues),			"issues":      criticalIssues,			"project":     payload.Project.Name,			"project_id":  payload.Project.ID,			"source":      "snyk",		eventPayload, _ := json.Marshal(map[string]interface{}{	if len(criticalIssues) > 0 {	}		}			criticalIssues = append(criticalIssues, fmt.Sprintf("%s (%s)", issue.Title, issue.Severity))		if issue.Severity == "critical" || issue.Severity == "high" {	for _, issue := range payload.NewIssues {	var criticalIssues []string	// Count critical/high new issues.	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload snykWebhookPayload	}		return		http.Error(w, "invalid signature", http.StatusUnauthorized)	if !a.verifySignature(r, body) {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *SnykAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound Snyk webhook events.}	return hmac.Equal([]byte(sig), []byte(expected))	expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))	mac.Write(body)	mac := hmac.New(sha256.New, []byte(a.webhookSecret))	}		return false	if sig == "" {	sig := r.Header.Get("X-Snyk-Signature")	}		return true	if a.webhookSecret == "" {func (a *SnykAdapter) verifySignature(r *http.Request, body []byte) bool {// verifySignature validates the Snyk webhook HMAC-SHA256 signature.}	http.ListenAndServe(":8102", mux)	log.Printf("Snyk adapter listening on :8102")	mux.HandleFunc("/api/v1/projects", adapter.HandleProjects)	mux.HandleFunc("/api/v1/vulnerabilities", adapter.HandleVulnerabilities)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:           bus,		httpClient:    &http.Client{},		webhookSecret: os.Getenv("SNYK_WEBHOOK_SECRET"),		orgID:         orgID,		apiToken:      apiToken,	adapter := &SnykAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("SNYK_ORG_ID is required")	if orgID == "" {	orgID := os.Getenv("SNYK_ORG_ID")	}		log.Fatal("SNYK_API_TOKEN is required")	if apiToken == "" {	apiToken := os.Getenv("SNYK_API_TOKEN")func main() {}	} `json:"results"`		} `json:"issues"`			} `json:"vulnerabilities"`				Severity string `json:"severity"`				Title    string `json:"title"`				ID       string `json:"id"`			Vulnerabilities []struct {		Issues struct {	Results []struct {type snykIssuesResponse struct {// snykIssuesResponse wraps the vulnerability list response.}	Projects []snykProject `json:"projects"`type snykProjectsResponse struct {// snykProjectsResponse is the list response from /org/{orgID}/projects.}	Type string `json:"type"`	Name string `json:"name"`	ID   string `json:"id"`type snykProject struct {// snykProject represents a Snyk project as returned by the REST API.}	} `json:"newIssues,omitempty"`		Severity string `json:"severity"`		Title    string `json:"title"`		ID       string `json:"id"`	NewIssues []struct {	} `json:"vulnerabilities,omitempty"`		CVSSv3   string `json:"CVSSv3"`		Severity string `json:"severity"`		Title    string `json:"title"`		ID       string `json:"id"`	Vulnerabilities []struct {	} `json:"project"`		Name string `json:"name"`		ID   string `json:"id"`	Project struct {type snykWebhookPayload struct {// snykWebhookPayload is the envelope Snyk sends for project events.}	bus           events.Bus	httpClient    *http.Client	webhookSecret string	orgID         string	apiToken      stringtype SnykAdapter struct {// SnykAdapter bridges Snyk vulnerability events with the Forge event bus.const snykAPIBase = "https://api.snyk.io/v1")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"	"encoding/hex"	"crypto/sha256"	"crypto/hmac"	"context"