package jenkins
package main

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"












































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("jenkins API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	}		req.Header.Set("Content-Type", "application/json")	if body != nil {	req.SetBasicAuth(a.user, a.apiToken)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, a.baseURL+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *JenkinsAdapter) jenkinsRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentRequested}, func(e events.Event) error {	ctx := context.Background()func (a *JenkinsAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.jenkinsRequest(r.Context(), http.MethodGet, jenkinsAPIBase, nil, &result); err != nil {		var result map[string]interface{}	case http.MethodGet:	switch r.Method {func (a *JenkinsAdapter) HandleJobs(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		w.WriteHeader(http.StatusCreated)		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.jenkinsRequest(r.Context(), http.MethodPost, path, nil, nil); err != nil {		path := fmt.Sprintf("/job/%s/build", job)	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.jenkinsRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		path := fmt.Sprintf("/job/%s%s", job, jenkinsAPIBase)		var result map[string]interface{}	case http.MethodGet:	switch r.Method {	}		return		http.Error(w, "job query parameter is required", http.StatusBadRequest)	if job == "" {	job := r.URL.Query().Get("job")func (a *JenkinsAdapter) HandleBuilds(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source": "jenkins",		"url":    p.Build.FullURL,		"status": p.Build.Status,		"build":  p.Build.Number,		"job":    p.Name,	ep, _ := json.Marshal(map[string]interface{}{func (a *JenkinsAdapter) handleBuildFailed(ctx context.Context, p jenkinsBuildEvent) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source": "jenkins",		"url":    p.Build.FullURL,		"build":  p.Build.Number,		"job":    p.Name,	ep, _ := json.Marshal(map[string]interface{}{func (a *JenkinsAdapter) handleBuildSuccess(ctx context.Context, p jenkinsBuildEvent) {}	}		log.Printf("failed to publish task started event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskStarted, Payload: ep}); err != nil {	})		"source": "jenkins",		"url":    p.Build.FullURL,		"build":  p.Build.Number,		"job":    p.Name,	ep, _ := json.Marshal(map[string]interface{}{func (a *JenkinsAdapter) handleBuildStarted(ctx context.Context, p jenkinsBuildEvent) {}	w.WriteHeader(http.StatusOK)	}		a.handleBuildStarted(r.Context(), payload)	case "STARTED":		}			a.handleBuildFailed(r.Context(), payload)		case "FAILURE", "ABORTED", "UNSTABLE":			a.handleBuildSuccess(r.Context(), payload)		case "SUCCESS":		switch payload.Build.Status {	case "COMPLETED":	switch payload.Build.Phase {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload jenkinsBuildEvent	}		}			return			http.Error(w, "invalid signature", http.StatusUnauthorized)		if !hmac.Equal([]byte(expected), []byte(sig)) {		expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))		mac.Write(body)		mac := hmac.New(sha256.New, []byte(a.webhookSecret))		sig := r.Header.Get("X-Jenkins-Signature")	if a.webhookSecret != "" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *JenkinsAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8111", mux)	log.Printf("Jenkins adapter listening on :8111")	mux.HandleFunc("/api/v1/jobs", adapter.HandleJobs)	mux.HandleFunc("/api/v1/builds", adapter.HandleBuilds)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:    &http.Client{},		bus:           bus,		webhookSecret: os.Getenv("JENKINS_WEBHOOK_SECRET"),		apiToken:      apiToken,		user:          user,		baseURL:       strings.TrimRight(baseURL, "/"),	adapter := &JenkinsAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("JENKINS_URL, JENKINS_USER, and JENKINS_API_TOKEN are required")	if baseURL == "" || user == "" || apiToken == "" {	apiToken := os.Getenv("JENKINS_API_TOKEN")	user := os.Getenv("JENKINS_USER")	baseURL := os.Getenv("JENKINS_URL")func main() {}	} `json:"build"`		FullURL  string `json:"full_url"`		URL      string `json:"url"`		Status   string `json:"status"`		Phase    string `json:"phase"`		Number   int    `json:"number"`	Build  struct {	Name   string `json:"name"`type jenkinsBuildEvent struct {}	httpClient    *http.Client	bus           events.Bus	webhookSecret string	apiToken      string	user          string	baseURL       stringtype JenkinsAdapter struct {const jenkinsAPIBase = "/api/json")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"