package azuredevopsrepos
package main

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)


































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("azure devops API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.SetBasicAuth("", a.pat)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, "https://dev.azure.com"+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *AzureDevOpsReposAdapter) adoRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.adoRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result map[string]interface{}		path := fmt.Sprintf("/%s/%s/_apis/git/repositories/%s/commits?api-version=7.0", a.organization, a.project, repoID)	case http.MethodGet:	switch r.Method {	}		return		http.Error(w, "repo_id query parameter is required", http.StatusBadRequest)	if repoID == "" {	repoID := r.URL.Query().Get("repo_id")func (a *AzureDevOpsReposAdapter) HandleCommits(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.adoRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result map[string]interface{}		path := fmt.Sprintf("/%s/%s/_apis/git/repositories/%s/refs?filter=heads&api-version=7.0", a.organization, a.project, repoID)	case http.MethodGet:	switch r.Method {	}		return		http.Error(w, "repo_id query parameter is required", http.StatusBadRequest)	if repoID == "" {	repoID := r.URL.Query().Get("repo_id")func (a *AzureDevOpsReposAdapter) HandleBranches(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.adoRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result map[string]interface{}		path := fmt.Sprintf("/%s/%s/_apis/git/repositories/%s/pullrequests?api-version=7.0", a.organization, a.project, repoID)	case http.MethodGet:	switch r.Method {	}		return		http.Error(w, "repo_id query parameter is required", http.StatusBadRequest)	if repoID == "" {	repoID := r.URL.Query().Get("repo_id")func (a *AzureDevOpsReposAdapter) HandlePullRequests(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source": "azuredevopsrepos",		"repo":   p.Resource.Repository.Name,		"pr_id":  p.Resource.PullRequestID,	ep, _ := json.Marshal(map[string]interface{}{func (a *AzureDevOpsReposAdapter) handlePRMerged(ctx context.Context, p adoPREvent) {}	}		log.Printf("failed to publish review requested event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.ReviewRequested, Payload: ep}); err != nil {	})		"source":  "azuredevopsrepos",		"url":     p.Resource.URL,		"repo":    p.Resource.Repository.Name,		"title":   p.Resource.Title,		"pr_id":   p.Resource.PullRequestID,	ep, _ := json.Marshal(map[string]interface{}{	}		return	if !strings.HasPrefix(branch, "forge/") {	branch := strings.TrimPrefix(p.Resource.SourceBranch, "refs/heads/")func (a *AzureDevOpsReposAdapter) handlePRCreated(ctx context.Context, p adoPREvent) {}	w.WriteHeader(http.StatusOK)	}		a.handlePRMerged(r.Context(), payload)	case "git.pullrequest.merged":		a.handlePRCreated(r.Context(), payload)	case "git.pullrequest.created", "git.pullrequest.updated":	switch payload.EventType {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload adoPREvent	}		}			return			http.Error(w, "invalid signature", http.StatusUnauthorized)		if !hmac.Equal([]byte(expected), []byte(sig)) {		expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))		mac.Write(body)		mac := hmac.New(sha256.New, []byte(a.webhookSecret))		sig := r.Header.Get("X-Hub-Signature-256")	if a.webhookSecret != "" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AzureDevOpsReposAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8110", mux)	log.Printf("Azure DevOps Repos adapter listening on :8110")	mux.HandleFunc("/api/v1/commits", adapter.HandleCommits)	mux.HandleFunc("/api/v1/branches", adapter.HandleBranches)	mux.HandleFunc("/api/v1/pulls", adapter.HandlePullRequests)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	}		httpClient:    &http.Client{},		bus:           bus,		webhookSecret: os.Getenv("AZURE_DEVOPS_REPOS_WEBHOOK_SECRET"),		pat:           pat,		project:       os.Getenv("AZURE_DEVOPS_PROJECT"),		organization:  org,	adapter := &AzureDevOpsReposAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("AZURE_DEVOPS_ORG and AZURE_DEVOPS_PAT are required")	if org == "" || pat == "" {	pat := os.Getenv("AZURE_DEVOPS_PAT")	org := os.Getenv("AZURE_DEVOPS_ORG")func main() {}	} `json:"resource"`		URL string `json:"url"`		} `json:"repository"`			Name string `json:"name"`			ID   string `json:"id"`		Repository    struct {		SourceBranch  string `json:"sourceRefName"`		Status        string `json:"status"`		Title         string `json:"title"`		PullRequestID int    `json:"pullRequestId"`	Resource  struct {	EventType string `json:"eventType"`type adoPREvent struct {}	httpClient    *http.Client	bus           events.Bus	webhookSecret string	pat           string	project       string	organization  stringtype AzureDevOpsReposAdapter struct {// REST endpoints to create branches, pull requests, and read commits.// Azure DevOps Repos adapter — handles Git repository webhooks and exposes