package newrelic
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)

const newRelicAPIBase = "https://api.newrelic.com/v2"














































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("new relic API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("X-Api-Key", a.apiKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, newRelicAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *NewRelicAdapter) nrRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.TaskCompleted}, func(e events.Event) error {	ctx := context.Background()func (a *NewRelicAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.nrRequest(r.Context(), http.MethodGet, "/alerts_violations.json?only_open=true", nil, &result); err != nil {		var result map[string]interface{}	case http.MethodGet:	switch r.Method {func (a *NewRelicAdapter) HandleViolations(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.nrRequest(r.Context(), http.MethodGet, "/alerts_policies.json", nil, &result); err != nil {		var result map[string]interface{}	case http.MethodGet:	switch r.Method {func (a *NewRelicAdapter) HandleAlerts(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":      "newrelic",		"policy":      p.PolicyName,		"incident_id": p.IncidentID,	ep, _ := json.Marshal(map[string]interface{}{func (a *NewRelicAdapter) handleAlertClosed(ctx context.Context, p newRelicAlertPayload) {}	}		log.Printf("failed to publish escalation event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {	})		"source":         "newrelic",		"details":        p.Details,		"severity":       p.Severity,		"condition":      p.ConditionName,		"policy":         p.PolicyName,		"incident_id":    p.IncidentID,	ep, _ := json.Marshal(map[string]interface{}{func (a *NewRelicAdapter) handleAlertOpened(ctx context.Context, p newRelicAlertPayload) {}	w.WriteHeader(http.StatusOK)	}		a.handleAlertClosed(r.Context(), payload)	case "closed":		}			a.handleAlertOpened(r.Context(), payload)		if payload.Severity == "CRITICAL" || payload.Severity == "WARNING" {	case "open":	switch payload.State {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload newRelicAlertPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *NewRelicAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8116", mux)	log.Printf("New Relic adapter listening on :8116")	mux.HandleFunc("/api/v1/violations", adapter.HandleViolations)	mux.HandleFunc("/api/v1/alerts", adapter.HandleAlerts)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient: &http.Client{},		bus:        bus,		accountID:  os.Getenv("NEWRELIC_ACCOUNT_ID"),		apiKey:     apiKey,	adapter := &NewRelicAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("NEWRELIC_API_KEY is required")	if apiKey == "" {	apiKey := os.Getenv("NEWRELIC_API_KEY")func main() {}	Data newRelicAlertPayload `json:"data"`type newRelicWebhookEnvelope struct {}	Details     string `json:"details"`	IncidentID  int    `json:"incident_id"`	ConditionName string `json:"condition_name"`	PolicyName  string `json:"policy_name"`	State       string `json:"state"`	Severity    string `json:"severity"`type newRelicAlertPayload struct {}	httpClient *http.Client	bus        events.Bus	accountID  string	apiKey     stringtype NewRelicAdapter struct {const newRelicAlertsBase = "https://api.newrelic.com/v2/alerts_violations.json"