package launchdarkly
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"





























































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("launchdarkly API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", a.apiKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, ldAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *LaunchDarklyAdapter) ldRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentApproved}, func(e events.Event) error {	ctx := context.Background()func (a *LaunchDarklyAdapter) subscribeToEvents() {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.ldRequest(r.Context(), http.MethodGet, fmt.Sprintf("/projects/%s/environments", projectKey), nil, &result); err != nil {	var result interface{}	}		projectKey = a.projectKey	if projectKey == "" {	projectKey := r.URL.Query().Get("project")	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *LaunchDarklyAdapter) HandleEnvironments(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.WriteHeader(http.StatusCreated)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.ldRequest(r.Context(), http.MethodPost, fmt.Sprintf("/flags/%s", projectKey), req, &result); err != nil {		var result interface{}		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req map[string]interface{}		}			projectKey = a.projectKey		if projectKey == "" {		projectKey := r.URL.Query().Get("project")	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.ldRequest(r.Context(), http.MethodGet, fmt.Sprintf("/flags/%s", projectKey), nil, &result); err != nil {		var result interface{}		}			projectKey = a.projectKey		if projectKey == "" {		projectKey := r.URL.Query().Get("project")	case http.MethodGet:	switch r.Method {func (a *LaunchDarklyAdapter) HandleFlags(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":    "launchdarkly",		"changes":   f.Changes,		"flag_name": f.Name,		"flag_key":  f.Key,	ep, _ := json.Marshal(map[string]interface{}{func (a *LaunchDarklyAdapter) handleFlagChanged(ctx context.Context, f ldFlagChange) {}	w.WriteHeader(http.StatusOK)	}		a.handleFlagChanged(r.Context(), payload.Data)	case "flag":	switch payload.Kind {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload ldWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *LaunchDarklyAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8127", mux)	log.Printf("LaunchDarkly adapter listening on :8127")	mux.HandleFunc("/api/v1/environments", adapter.HandleEnvironments)	mux.HandleFunc("/api/v1/flags", adapter.HandleFlags)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient: &http.Client{},		bus:        bus,		projectKey: os.Getenv("LAUNCHDARKLY_PROJECT_KEY"),		apiKey:     apiKey,	adapter := &LaunchDarklyAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("LAUNCHDARKLY_API_KEY is required")	if apiKey == "" {	apiKey := os.Getenv("LAUNCHDARKLY_API_KEY")func main() {}	Data        ldFlagChange `json:"data,omitempty"`	AcccessToken string    `json:"acccessToken,omitempty"`	Kind        string     `json:"kind"`type ldWebhookPayload struct {}	Changes map[string]interface{} `json:"changes"`	Name   string `json:"name"`	Key    string `json:"key"`	Kind   string `json:"kind"`type ldFlagChange struct {}	httpClient *http.Client	bus        events.Bus	projectKey string	apiKey     stringtype LaunchDarklyAdapter struct {const ldAPIBase = "https://app.launchdarkly.com/api/v2")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"