package azuredevopsboards
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)

// Azure DevOps Boards adapter handles work item webhooks and exposes REST








































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("azure devops boards API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json-patch+json")	req.SetBasicAuth("", a.pat)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, adoBoardsAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *AzureDevOpsBoardsAdapter) adoRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	}, func(e events.Event) error {		events.TaskBlocked,		events.TaskFailed,		events.TaskCompleted,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *AzureDevOpsBoardsAdapter) subscribeToEvents() {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.adoRequest(r.Context(), http.MethodPatch, path, req, &result); err != nil {	var result map[string]interface{}	path := fmt.Sprintf("/%s/%s/_apis/wit/workitems/%s?api-version=7.0", a.organization, a.project, id)	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req interface{}	}		return		http.Error(w, "id query parameter is required", http.StatusBadRequest)	if id == "" {	id := r.URL.Query().Get("id")	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AzureDevOpsBoardsAdapter) HandleTransitions(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.adoRequest(r.Context(), http.MethodPost, path, req, &result); err != nil {		var result map[string]interface{}		path := fmt.Sprintf("/%s/%s/_apis/wit/workitems/$Task?api-version=7.0", a.organization, a.project)		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req interface{}	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.adoRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result map[string]interface{}		path += "?api-version=7.0"		}			path += "/" + id		if id != "" {		path := fmt.Sprintf("/%s/%s/_apis/wit/workitems", a.organization, a.project)		id := r.URL.Query().Get("id")	case http.MethodGet:	switch r.Method {func (a *AzureDevOpsBoardsAdapter) HandleWorkItems(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source":       "azuredevopsboards",		"work_item_id": p.Resource.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *AzureDevOpsBoardsAdapter) handleWorkItemRemoved(ctx context.Context, p adoWorkItemEvent) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":       "azuredevopsboards",		"state":        p.Resource.Fields.State.NewValue,		"work_item_id": p.Resource.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *AzureDevOpsBoardsAdapter) handleWorkItemCompleted(ctx context.Context, p adoWorkItemEvent) {}	}		log.Printf("failed to publish task created event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCreated, Payload: ep}); err != nil {	})		"source":       "azuredevopsboards",		"url":          p.Resource.URL,		"title":        p.Resource.Fields.Title.NewValue,		"work_item_id": p.Resource.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *AzureDevOpsBoardsAdapter) handleWorkItemCreated(ctx context.Context, p adoWorkItemEvent) {}	w.WriteHeader(http.StatusOK)	}		}			a.handleWorkItemRemoved(r.Context(), payload)		case "Removed":			a.handleWorkItemCompleted(r.Context(), payload)		case "Done", "Closed", "Resolved":		switch newState {		newState := payload.Resource.Fields.State.NewValue	case "workitem.updated":		}			a.handleWorkItemCreated(r.Context(), payload)		if strings.Contains(tags, "forge") {		tags := payload.Resource.Fields.Tags.NewValue	case "workitem.created":	switch payload.EventType {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload adoWorkItemEvent	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AzureDevOpsBoardsAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8124", mux)	log.Printf("Azure DevOps Boards adapter listening on :8124")	mux.HandleFunc("/api/v1/transitions", adapter.HandleTransitions)	mux.HandleFunc("/api/v1/workitems", adapter.HandleWorkItems)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:   &http.Client{},		bus:          bus,		pat:          pat,		project:      os.Getenv("AZURE_DEVOPS_PROJECT"),		organization: org,	adapter := &AzureDevOpsBoardsAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("AZURE_DEVOPS_ORG and AZURE_DEVOPS_PAT are required")	if org == "" || pat == "" {	pat := os.Getenv("AZURE_DEVOPS_PAT")	org := os.Getenv("AZURE_DEVOPS_ORG")func main() {}	} `json:"resource"`		URL string `json:"url"`		} `json:"fields"`			Tags      struct{ NewValue string `json:"newValue"` } `json:"System.Tags"`			AssignedTo struct{ NewValue string `json:"newValue"` } `json:"System.AssignedTo"`			WorkType  struct{ Value string `json:"$value"` } `json:"System.WorkItemType"`			State     struct{ NewValue string `json:"newValue"` } `json:"System.State"`			Title     struct{ NewValue string `json:"newValue"` } `json:"System.Title"`		Fields struct {		Rev    int    `json:"rev"`		ID     int    `json:"id"`	Resource  struct {	EventType string `json:"eventType"`type adoWorkItemEvent struct {}	httpClient   *http.Client	bus          events.Bus	pat          string	project      string	organization stringtype AzureDevOpsBoardsAdapter struct {const adoBoardsAPIBase = "https://dev.azure.com"// counterpart to the azuredevopsrepos adapter).// endpoints to create/update Azure Boards work items (the Boards-only