package splitio
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)




































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("split.io API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "Bearer "+a.apiKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, splitAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *SplitIOAdapter) splitRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentApproved}, func(e events.Event) error {	ctx := context.Background()func (a *SplitIOAdapter) subscribeToEvents() {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.splitRequest(r.Context(), http.MethodPatch, path, req, &result); err != nil {	var result interface{}	path := fmt.Sprintf("/splits/ws/%s/%s/environments/%s", a.workspace, splitName, env)	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req map[string]interface{}	}		env = a.environment	if env == "" {	env := r.URL.Query().Get("env")	}		return		http.Error(w, "name query parameter is required", http.StatusBadRequest)	if splitName == "" {	splitName := r.URL.Query().Get("name")	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *SplitIOAdapter) HandleToggles(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.WriteHeader(http.StatusCreated)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.splitRequest(r.Context(), http.MethodPost, path, req, &result); err != nil {		var result interface{}		path := fmt.Sprintf("/splits/ws/%s", a.workspace)		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req map[string]interface{}	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.splitRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result interface{}		}			path += "/" + splitName		if splitName != "" {		path := fmt.Sprintf("/splits/ws/%s", a.workspace)		splitName := r.URL.Query().Get("name")	case http.MethodGet:	switch r.Method {func (a *SplitIOAdapter) HandleSplits(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task completed event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {		})			"source":      "splitio",			"treatment":   payload.Feature.Treatment,			"environment": payload.Feature.Environment,			"split_name":  payload.Feature.Name,		ep, _ := json.Marshal(map[string]interface{}{	case "SPLIT_UPDATED":		}			log.Printf("failed to publish escalation event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {		})			"source":      "splitio",			"environment": payload.Feature.Environment,			"split_name":  payload.Feature.Name,		ep, _ := json.Marshal(map[string]interface{}{	case "SPLIT_KILLED":	switch payload.Type {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload splitWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *SplitIOAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8128", mux)	log.Printf("Split.io adapter listening on :8128")	mux.HandleFunc("/api/v1/toggles", adapter.HandleToggles)	mux.HandleFunc("/api/v1/splits", adapter.HandleSplits)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:  &http.Client{},		bus:         bus,		workspace:   os.Getenv("SPLIT_WORKSPACE_ID"),		environment: os.Getenv("SPLIT_ENVIRONMENT"),		apiKey:      apiKey,	adapter := &SplitIOAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("SPLIT_API_KEY is required")	if apiKey == "" {	apiKey := os.Getenv("SPLIT_API_KEY")func main() {}	} `json:"feature"`		Treatment   string `json:"defaultTreatment"`		Killed      bool   `json:"killed"`		Environment string `json:"environment"`		Name        string `json:"name"`	Feature struct {	Type    string `json:"type"`type splitWebhookPayload struct {}	httpClient  *http.Client	bus         events.Bus	workspace   string	environment string	apiKey      stringtype SplitIOAdapter struct {const splitAPIBase = "https://api.split.io/internal/api/v2"