package argocd
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

















































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("argocd API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "Bearer "+a.token)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, a.baseURL+argoCDAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *ArgoCDAdapter) argoRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentRequested}, func(e events.Event) error {	ctx := context.Background()func (a *ArgoCDAdapter) subscribeToEvents() {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.argoRequest(r.Context(), http.MethodPost, fmt.Sprintf("/applications/%s/sync", appName), map[string]interface{}{}, &result); err != nil {	var result map[string]interface{}	}		return		http.Error(w, "app query parameter is required", http.StatusBadRequest)	if appName == "" {	appName := r.URL.Query().Get("app")	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *ArgoCDAdapter) HandleSync(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.argoRequest(r.Context(), http.MethodGet, "/applications", nil, &result); err != nil {		var result map[string]interface{}	case http.MethodGet:	switch r.Method {func (a *ArgoCDAdapter) HandleApps(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task started event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskStarted, Payload: ep}); err != nil {	})		"source":   "argocd",		"app_name": app.Metadata.Name,	ep, _ := json.Marshal(map[string]interface{}{func (a *ArgoCDAdapter) handleSyncRunning(ctx context.Context, app argoCDApp) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source":   "argocd",		"message":  app.Status.OperationState.Message,		"app_name": app.Metadata.Name,	ep, _ := json.Marshal(map[string]interface{}{func (a *ArgoCDAdapter) handleSyncFailed(ctx context.Context, app argoCDApp) {}	}		log.Printf("failed to publish deployment approved event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.DeploymentApproved, Payload: ep}); err != nil {	})		"source":      "argocd",		"health":      app.Status.Health.Status,		"sync_status": app.Status.Sync.Status,		"app_name":    app.Metadata.Name,	ep, _ := json.Marshal(map[string]interface{}{func (a *ArgoCDAdapter) handleSyncSucceeded(ctx context.Context, app argoCDApp) {}	w.WriteHeader(http.StatusOK)	}		}			a.handleSyncRunning(r.Context(), app)		case "Running":			a.handleSyncFailed(r.Context(), app)		case "Failed", "Error":			a.handleSyncSucceeded(r.Context(), app)		case "Succeeded":		switch app.Status.OperationState.Phase {	if app.Status.OperationState != nil {	app := payload.Application	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload argoCDWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *ArgoCDAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8113", mux)	log.Printf("ArgoCD adapter listening on :8113")	mux.HandleFunc("/api/v1/sync", adapter.HandleSync)	mux.HandleFunc("/api/v1/apps", adapter.HandleApps)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient: &http.Client{},		bus:        bus,		token:      token,		baseURL:    strings.TrimRight(baseURL, "/"),	adapter := &ArgoCDAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("ARGOCD_URL and ARGOCD_TOKEN are required")	if baseURL == "" || token == "" {	token := os.Getenv("ARGOCD_TOKEN")	baseURL := os.Getenv("ARGOCD_URL")func main() {}	Application argoCDApp `json:"application"`type argoCDWebhookPayload struct {}	} `json:"status"`		} `json:"health"`			Status string `json:"status"`		Health struct {		} `json:"sync"`			Status string `json:"status"`		Sync           struct {		OperationState *argoCDAppStatus `json:"operationState"`	Status struct {	} `json:"metadata"`		Name string `json:"name"`	Metadata struct {type argoCDApp struct {}	Message string `json:"message"`	Phase   string `json:"phase"`type argoCDAppStatus struct {}	httpClient *http.Client	bus        events.Bus	token      string	baseURL    stringtype ArgoCDAdapter struct {const argoCDAPIBase = "/api/v1")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"