package browserstack
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)

// BrowserStack / Sauce Labs adapter ingests automated test execution results
// from cloud browser/device test platforms and routes outcomes to Forge's
// message bus.















































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("sauce labs API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.SetBasicAuth(a.slUser, a.slAccessKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, sauceLabsAPIBase+path, bodyReader)	}		method = http.MethodPost	if bodyReader != nil {	method := http.MethodGet	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *BrowserStackAdapter) slRequest(ctx context.Context, path string, body interface{}, out interface{}) error {}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("browserstack API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.SetBasicAuth(a.bsUser, a.bsAccessKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, browserStackAPIBase+path, bodyReader)	}		method = http.MethodPost	if bodyReader != nil {	method := http.MethodGet	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *BrowserStackAdapter) bsRequest(ctx context.Context, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.ReviewApproved}, func(e events.Event) error {	ctx := context.Background()func (a *BrowserStackAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.bsRequest(r.Context(), fmt.Sprintf("/builds/%s/sessions.json", buildID), nil, &result); err != nil {		var result interface{}	case http.MethodGet:	switch r.Method {	}		return		http.Error(w, "build_id query parameter is required", http.StatusBadRequest)	if buildID == "" {	buildID := r.URL.Query().Get("build_id")func (a *BrowserStackAdapter) HandleSessions(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err != nil {		}			return			http.Error(w, "unsupported provider", http.StatusBadRequest)		default:			err = a.slRequest(r.Context(), fmt.Sprintf("/%s/builds", a.slUser), nil, &result)		case "saucelabs":			err = a.bsRequest(r.Context(), "/builds.json", nil, &result)		case "browserstack":		switch provider {		var err error		var result interface{}	case http.MethodGet:	switch r.Method {	}		provider = "browserstack"	if provider == "" {	provider := r.URL.Query().Get("provider")func (a *BrowserStackAdapter) HandleBuilds(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})			})				"source":   "saucelabs",				"passed":   payload.Passed,				"name":     payload.Name,				"build_id": payload.ID,			ep, _ := json.Marshal(map[string]interface{}{		} else {			a.bus.Publish(r.Context(), events.Event{Type: events.TaskBlocked, Payload: ep})			})				"source":   "saucelabs",				"passed":   payload.Passed,				"failed":   payload.Failed,				"name":     payload.Name,				"build_id": payload.ID,			ep, _ := json.Marshal(map[string]interface{}{		if payload.Failed > 0 {	if payload.Status == "complete" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload sauceLabsBuildPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *BrowserStackAdapter) HandleSauceLabsWebhook(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})			})				"source":     "browserstack",				"passed":     payload.PassedCount,				"build_name": payload.BuildName,				"build_id":   payload.BuildID,			ep, _ := json.Marshal(map[string]interface{}{		} else {			a.bus.Publish(r.Context(), events.Event{Type: events.TaskBlocked, Payload: ep})			})				"source":     "browserstack",				"passed":     payload.PassedCount,				"failed":     payload.FailedCount,				"build_name": payload.BuildName,				"build_id":   payload.BuildID,			ep, _ := json.Marshal(map[string]interface{}{		if payload.FailedCount > 0 {	case "done":	switch payload.Status {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload browserStackBuildPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *BrowserStackAdapter) HandleBrowserStackWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8131", mux)	log.Printf("BrowserStack / Sauce Labs adapter listening on :8131")	mux.HandleFunc("/api/v1/sessions", adapter.HandleSessions)	mux.HandleFunc("/api/v1/builds", adapter.HandleBuilds)	mux.HandleFunc("/webhook/saucelabs", adapter.HandleSauceLabsWebhook)	mux.HandleFunc("/webhook/browserstack", adapter.HandleBrowserStackWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:  &http.Client{},		bus:         bus,		slAccessKey: os.Getenv("SAUCE_ACCESS_KEY"),		slUser:      os.Getenv("SAUCE_USERNAME"),		bsAccessKey: os.Getenv("BROWSERSTACK_ACCESS_KEY"),		bsUser:      os.Getenv("BROWSERSTACK_USER"),	adapter := &BrowserStackAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")func main() {}	Failed int    `json:"failed"`	Passed int    `json:"passed"`	Status string `json:"status"`	Name   string `json:"name"`	ID     string `json:"id"`type sauceLabsBuildPayload struct {}	PassedCount int    `json:"passed_count"`	FailedCount int    `json:"failed_count"`	TotalCount  int    `json:"total_count"`	Duration    int    `json:"duration"`	Status      string `json:"status"`	BuildName   string `json:"build_name"`	BuildID     string `json:"build_id"`type browserStackBuildPayload struct {}	httpClient  *http.Client	bus         events.Bus	slAccessKey string	slUser      string	bsAccessKey string	bsUser      stringtype BrowserStackAdapter struct {const sauceLabsAPIBase = "https://api.us-west-1.saucelabs.com/rest/v1"const browserStackAPIBase = "https://api.browserstack.com/automate/v1"