package azuremonitor
package main

import (
	"context"
	"encoding/json"
	"fmt"

































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("azure devops API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.SetBasicAuth("", a.pat)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, azureDevOpsAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *AzureMonitorAdapter) adoRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentRequested}, func(e events.Event) error {	ctx := context.Background()func (a *AzureMonitorAdapter) subscribeToEvents() {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.adoRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {	var result map[string]interface{}	path := fmt.Sprintf("/%s/%s/_apis/pipelines?api-version=7.0", a.organization, a.project)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *AzureMonitorAdapter) HandlePipelines(w http.ResponseWriter, r *http.Request) {}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		"message": "Use Azure Monitor REST API with subscription credentials",	result := map[string]interface{}{	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *AzureMonitorAdapter) HandleAlerts(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			a.bus.Publish(r.Context(), events.Event{Type: events.TaskFailed, Payload: ep})			})				"source":   "azure_devops",				"result":   payload.Resource.Result,				"name":     payload.Resource.Name,				"build_id": payload.Resource.ID,			ep, _ := json.Marshal(map[string]interface{}{		case "failed", "canceled":			a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})			})				"source":   "azure_devops",				"url":      payload.Resource.Links.Web.Href,				"name":     payload.Resource.Name,				"build_id": payload.Resource.ID,			ep, _ := json.Marshal(map[string]interface{}{		case "succeeded":		switch payload.Resource.Result {	case "build.complete":	switch payload.EventType {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload adoPipelineEvent	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AzureMonitorAdapter) HandleDevOpsWebhook(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task completed event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {		})			"source":   "azure_monitor",			"rule":     ess.AlertRule,			"alert_id": ess.AlertID,		ep, _ := json.Marshal(map[string]interface{}{	case "Resolved":		}			log.Printf("failed to publish escalation event: %v", err)		if err := a.bus.Publish(r.Context(), events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {		})			"source":     "azure_monitor",			"description": ess.Description,			"resource":   ess.TargetResource,			"severity":   ess.Severity,			"rule":       ess.AlertRule,			"alert_id":   ess.AlertID,		ep, _ := json.Marshal(map[string]interface{}{	case "Fired":	switch ess.MonitorCondition {	ess := alert.Data.Essentials	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&alert); err != nil {	var alert azureMonitorAlert	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AzureMonitorAdapter) HandleMonitorWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8119", mux)	log.Printf("Azure Monitor / Azure DevOps adapter listening on :8119")	mux.HandleFunc("/api/v1/pipelines", adapter.HandlePipelines)	mux.HandleFunc("/api/v1/alerts", adapter.HandleAlerts)	mux.HandleFunc("/webhook/devops", adapter.HandleDevOpsWebhook)	mux.HandleFunc("/webhook/monitor", adapter.HandleMonitorWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:   &http.Client{},		bus:          bus,		pat:          os.Getenv("AZURE_DEVOPS_PAT"),		project:      os.Getenv("AZURE_DEVOPS_PROJECT"),		organization: os.Getenv("AZURE_DEVOPS_ORG"),	adapter := &AzureMonitorAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")func main() {}	} `json:"resource"`		} `json:"_links"`			Web struct{ Href string `json:"href"` } `json:"web"`		Links  struct {		URL    string `json:"_links"`		State  string `json:"state"`		Result string `json:"result"`		Name   string `json:"name"`		ID     int    `json:"id"`	Resource  struct {	EventType string `json:"eventType"`type adoPipelineEvent struct {}	SchemaID string `json:"schemaId"`	} `json:"data"`		} `json:"essentials"`			Description     string `json:"description"`			TargetResource  string `json:"targetResource"`			MonitorCondition string `json:"monitorCondition"`			Severity        string `json:"severity"`			AlertRule       string `json:"alertRule"`			AlertID         string `json:"alertId"`		Essentials struct {	Data struct {type azureMonitorAlert struct {}	httpClient   *http.Client	bus          events.Bus	pat          string	project      string	organization stringtype AzureMonitorAdapter struct {const azureDevOpsAPIBase = "https://dev.azure.com"// release events).// webhooks (alerts) and Azure DevOps service hook events (pipeline runs,// Azure Monitor / Azure DevOps adapter handles Azure Monitor action group)	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"