package opsgenie
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"











































































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil && resp.StatusCode != http.StatusNoContent {	}		return fmt.Errorf("opsgenie API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "GenieKey "+a.apiKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, opsgenieAPIBase+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *OpsgenieAdapter) ogRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// ogRequest is a helper that executes an authenticated Opsgenie REST API call.}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		w.WriteHeader(http.StatusOK)		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.ogRequest(r.Context(), http.MethodPost, "/alerts/"+alertID+"/acknowledge", ackReq, nil); err != nil {		}			Source: "forge",			Note:   r.URL.Query().Get("note"),		ackReq := ogAcknowledgeAlertRequest{		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if alertID == "" {		alertID := r.URL.Query().Get("id")	case http.MethodPatch:		w.WriteHeader(http.StatusNoContent)		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.ogRequest(r.Context(), http.MethodPost, "/alerts/"+alertID+"/close", closeReq, nil); err != nil {		}			Source: "forge",			Note:   r.URL.Query().Get("note"),		closeReq := ogCloseAlertRequest{		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if alertID == "" {		alertID := r.URL.Query().Get("id")	case http.MethodDelete:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.ogRequest(r.Context(), http.MethodPost, "/alerts", req, &result); err != nil {		var result ogCreateAlertResponse		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req ogCreateAlertRequest	case http.MethodPost:	switch r.Method {func (a *OpsgenieAdapter) HandleAlerts(w http.ResponseWriter, r *http.Request) {// HandleAlerts exposes a REST endpoint so other services can create/close/acknowledge alerts.}	return a.ogRequest(context.Background(), http.MethodPost, "/alerts", req, nil)	}		Details:     details,		Priority:    "P2",		Tags:        tags,		Description: payload.Reason,		Message:     message,	req := ogCreateAlertRequest{	}		details["reason"] = payload.Reason	if payload.Reason != "" {	}		details["jira_key"] = payload.JiraKey	if payload.JiraKey != "" {	}		"task_id": payload.TaskID,	details := map[string]string{	}		tags = append(tags, payload.JiraKey)	if payload.JiraKey != "" {	tags := []string{"forge"}	}		message = fmt.Sprintf("Forge: %s — %s", payload.JiraKey, payload.Reason)	if payload.JiraKey != "" {	message := fmt.Sprintf("Forge: task %s failed", payload.TaskID)	}		return nil	if payload.Source == "opsgenie" {	// Skip alerts that originated from Opsgenie to avoid loops.	json.Unmarshal(e.Payload, &payload)	}		Source  string `json:"source"`		Reason  string `json:"reason"`		JiraKey string `json:"jira_key"`		TaskID  string `json:"task_id"`	var payload struct {func (a *OpsgenieAdapter) createAlert(e events.Event) error {}	})		return nil		}			return a.createAlert(e)		case events.TaskFailed:			return a.createAlert(e)		case events.EscalationCreated:		switch e.Type {	}, func(e events.Event) error {		events.TaskFailed,		events.EscalationCreated,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *OpsgenieAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge events and creates/closes Opsgenie alerts.}	log.Printf("Opsgenie alert acknowledged: %s (%s)", alert.AlertID, alert.Message)func (a *OpsgenieAdapter) handleAlertAcknowledged(ctx context.Context, alert ogAlert) {}	}		log.Printf("failed to publish task completed event: %v", err)	}); err != nil {		Payload: payload,		Type:    events.TaskCompleted,	if err := a.bus.Publish(ctx, events.Event{	})		"source":   "opsgenie",		"message":  alert.Message,		"alert_id": alert.AlertID,	payload, _ := json.Marshal(map[string]interface{}{func (a *OpsgenieAdapter) handleAlertClosed(ctx context.Context, alert ogAlert) {}	}		log.Printf("failed to publish escalation event: %v", err)	}); err != nil {		Payload: payload,		Type:    events.EscalationCreated,	if err := a.bus.Publish(ctx, events.Event{	})		"source":   "opsgenie",		"tags":     alert.Tags,		"message":  alert.Message,		"alert_id": alert.AlertID,	payload, _ := json.Marshal(map[string]interface{}{func (a *OpsgenieAdapter) handleAlertCreated(ctx context.Context, alert ogAlert) {}	w.WriteHeader(http.StatusOK)	}		a.handleAlertAcknowledged(r.Context(), payload.Alert)	case "Acknowledge":		a.handleAlertClosed(r.Context(), payload.Alert)	case "Close":		a.handleAlertCreated(r.Context(), payload.Alert)	case "Create":	switch payload.Action {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload ogWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *OpsgenieAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound Opsgenie webhook events.}	http.ListenAndServe(":8099", mux)	log.Printf("Opsgenie adapter listening on :8099")	mux.HandleFunc("/api/v1/alerts", adapter.HandleAlerts)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:        bus,		httpClient: &http.Client{},		apiKey:     apiKey,	adapter := &OpsgenieAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("OPSGENIE_API_KEY is required")	if apiKey == "" {	apiKey := os.Getenv("OPSGENIE_API_KEY")func main() {}	Source string `json:"source,omitempty"`	Note   string `json:"note,omitempty"`type ogAcknowledgeAlertRequest struct {}	Source string `json:"source,omitempty"`	Note   string `json:"note,omitempty"`type ogCloseAlertRequest struct {}	RequestID string `json:"requestId"`	Result    string `json:"result"`type ogCreateAlertResponse struct {}	Details     map[string]string `json:"details,omitempty"`	Priority    string            `json:"priority,omitempty"`	Tags        []string          `json:"tags,omitempty"`	Description string            `json:"description,omitempty"`	Message     string            `json:"message"`type ogCreateAlertRequest struct {// Opsgenie REST API request/response types}	Tags    []string `json:"tags"`	Status  string `json:"status"`	Message string `json:"message"`	AlertID string `json:"alertId"`type ogAlert struct {}	Alert  ogAlert  `json:"alert"`	Action string   `json:"action"`type ogWebhookPayload struct {// Opsgenie webhook payload structures}	bus        events.Bus	httpClient *http.Client	apiKey     stringtype OpsgenieAdapter struct {const opsgenieAPIBase = "https://api.opsgenie.com/v2")	"github.com/dotrage/forge-adp/pkg/events"	"os"	"net/http"	"log"	"io"