package sonarqube
package main

import (
	"bytes"
	"context"
	"crypto/hmac"
























































































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("sonarqube API error %d: %s", resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	}		req.Header.Set("Content-Type", "application/json")	if body != nil {	req.SetBasicAuth(a.token, "")	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, a.baseURL+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *SonarQubeAdapter) sonarRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// sonarRequest is a helper that executes an authenticated SonarQube API call.}	})		return nil		// Future: trigger a SonarQube background task when a PR review is requested.	}, func(e events.Event) error {		events.ReviewRequested,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *SonarQubeAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge events that should trigger SonarQube actions.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.sonarRequest(r.Context(), http.MethodGet, "/api/qualitygates/list", nil, &result); err != nil {	var result sonarQualityGatesResponse	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *SonarQubeAdapter) HandleQualityGates(w http.ResponseWriter, r *http.Request) {// HandleQualityGates lists the configured SonarQube quality gates.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	); err != nil {		nil, &result,		"/api/issues/search?"+q.Encode(),	if err := a.sonarRequest(r.Context(), http.MethodGet,	var result sonarIssuesResponse	q.Set("resolved", "false")	}		q.Set("statuses", status)	if status := r.URL.Query().Get("statuses"); status != "" {	}		q.Set("severities", sev)	if sev := r.URL.Query().Get("severities"); sev != "" {	}		q.Set("componentKeys", pk)	if pk := r.URL.Query().Get("project_key"); pk != "" {	q := url.Values{}	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *SonarQubeAdapter) HandleIssues(w http.ResponseWriter, r *http.Request) {// HandleIssues proxies issue searches to SonarQube.}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task failed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskFailed,		if err := a.bus.Publish(r.Context(), events.Event{		})			"status":      payload.Status,			"task_id":     payload.TaskID,			"project_key": payload.Project.Key,			"project":     payload.Project.Name,			"source":      "sonarqube",		eventPayload, _ := json.Marshal(map[string]interface{}{	case "FAILED", "CANCELLED":		}			}				log.Printf("failed to publish escalation event: %v", err)			}); err != nil {				Payload: eventPayload,				Type:    events.EscalationCreated,			if err := a.bus.Publish(r.Context(), events.Event{			})				"reason":             fmt.Sprintf("SonarQube quality gate '%s' failed for project %s", payload.QualityGate.Name, payload.Project.Name),				"failed_conditions":  failedConditions,				"quality_gate":       payload.QualityGate.Name,				"project_url":        payload.Project.URL,				"project_key":        payload.Project.Key,				"project":            payload.Project.Name,				"source":             "sonarqube",			eventPayload, _ := json.Marshal(map[string]interface{}{			}				}					failedConditions = append(failedConditions, fmt.Sprintf("%s (value: %s, threshold: %s)", c.Metric, c.Value, c.ErrorThreshold))				if c.Status == "ERROR" {			for _, c := range payload.QualityGate.Conditions {			var failedConditions []string			// Analysis succeeded but quality gate failed — surface to the bus as a blocker.		if payload.QualityGate != nil && payload.QualityGate.Status == "ERROR" {	case "SUCCESS":	switch payload.Status {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload sonarWebhookPayload	}		return		http.Error(w, "invalid signature", http.StatusUnauthorized)	if !a.verifySignature(r, body) {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *SonarQubeAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound SonarQube analysis events.}	return hmac.Equal([]byte(sig), []byte(expected))	expected := hex.EncodeToString(mac.Sum(nil))	mac.Write(body)	mac := hmac.New(sha256.New, []byte(a.webhookSecret))	}		return false	if sig == "" {	sig := r.Header.Get("X-Sonar-Webhook-HMAC-SHA256")	}		return true	if a.webhookSecret == "" {func (a *SonarQubeAdapter) verifySignature(r *http.Request, body []byte) bool {// verifySignature validates the SonarQube webhook HMAC-SHA256 payload checksum.}	http.ListenAndServe(":8103", mux)	log.Printf("SonarQube adapter listening on :8103")	mux.HandleFunc("/api/v1/qualitygates", adapter.HandleQualityGates)	mux.HandleFunc("/api/v1/issues", adapter.HandleIssues)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:           bus,		httpClient:    &http.Client{},		webhookSecret: os.Getenv("SONARQUBE_WEBHOOK_SECRET"),		token:         token,		baseURL:       strings.TrimRight(baseURL, "/"),	adapter := &SonarQubeAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("SONARQUBE_TOKEN is required")	if token == "" {	token := os.Getenv("SONARQUBE_TOKEN")	}		log.Fatal("SONARQUBE_URL is required")	if baseURL == "" {	baseURL := os.Getenv("SONARQUBE_URL")func main() {}	QualityGates []sonarQualityGate `json:"qualitygates"`type sonarQualityGatesResponse struct {// sonarQualityGatesResponse wraps the list of quality gates.}	} `json:"conditions"`		Error    string `json:"error"`		Operator string `json:"op"`		Metric   string `json:"metric"`	Conditions []struct {	IsBuiltIn  bool   `json:"isBuiltIn"`	IsDefault  bool   `json:"isDefault"`	Name       string `json:"name"`	ID         string `json:"id"`type sonarQualityGate struct {// sonarQualityGate represents a quality gate definition.}	Issues []sonarIssue `json:"issues"`	Total  int          `json:"total"`type sonarIssuesResponse struct {// sonarIssuesResponse wraps the SonarQube issues search response.}	Type     string `json:"type"`	Status   string `json:"status"`	Message  string `json:"message"`	Severity string `json:"severity"`	Rule     string `json:"rule"`	Key      string `json:"key"`type sonarIssue struct {// sonarIssue represents a SonarQube code issue.}	} `json:"branch,omitempty"`		URL  string `json:"url"`		Type string `json:"type"`		Name string `json:"name"`	Branch *struct {	} `json:"qualityGate,omitempty"`		} `json:"conditions"`			ErrorThreshold string `json:"errorThreshold"`			Status     string `json:"status"`			Value      string `json:"value"`			Operator   string `json:"operator"`			Metric     string `json:"metric"`		Conditions []struct {		Status     string `json:"status"`		Name       string `json:"name"`	QualityGate *struct {	} `json:"project"`		URL  string `json:"url"`		Name string `json:"name"`		Key  string `json:"key"`	Project struct {	} `json:"analysis"`		Date string `json:"date"`		Key  string `json:"key"`	Analysis struct {	Status   string `json:"status"`	TaskID   string `json:"taskId"`type sonarWebhookPayload struct {// sonarWebhookPayload is the envelope SonarQube sends for analysis events.}	bus           events.Bus	httpClient    *http.Client	webhookSecret string	token         string	baseURL       stringtype SonarQubeAdapter struct {// SonarQubeAdapter bridges SonarQube analysis events with the Forge event bus.)	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/url"	"net/http"	"log"	"io"	"fmt"	"encoding/json"	"encoding/hex"	"crypto/sha256"