package githubactions
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)




























































































































































































































































}	return json.NewDecoder(resp.Body).Decode(out)	}		return fmt.Errorf("gitlab API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	}		req.Header.Set("PRIVATE-TOKEN", a.gitlabToken)	if a.gitlabToken != "" {	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, http.MethodGet, gitlabAPIBase+path, nil)func (a *CICDAdapter) glRequest(ctx context.Context, path string, out interface{}) error {}	return json.NewDecoder(resp.Body).Decode(out)	}		return fmt.Errorf("github API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")	}		req.Header.Set("Authorization", "Bearer "+a.githubToken)	if a.githubToken != "" {	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, http.MethodGet, githubAPIBase+path, nil)func (a *CICDAdapter) ghRequest(ctx context.Context, path string, out interface{}) error {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, reqErr.Error(), http.StatusInternalServerError)		if reqErr != nil {		}			return			http.Error(w, "unsupported provider", http.StatusBadRequest)		default:			reqErr = a.glRequest(r.Context(), path, &result)			path := fmt.Sprintf("/projects/%s/pipelines", strings.ReplaceAll(repo, "/", "%2F"))		case "gitlab":			reqErr = a.ghRequest(r.Context(), path, &result)			path := fmt.Sprintf("/repos/%s/actions/runs", repo)		case "github":		switch provider {		var reqErr error		var result map[string]interface{}		}			return			http.Error(w, "provider and repo query parameters are required", http.StatusBadRequest)		if provider == "" || repo == "" {		repo := r.URL.Query().Get("repo")		provider := r.URL.Query().Get("provider")	case http.MethodGet:	switch r.Method {func (a *CICDAdapter) HandleRuns(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source":      "gitlab_ci",		"project":     p.Project.PathWithNamespace,		"status":      p.ObjectAttributes.Status,		"pipeline_id": p.ObjectAttributes.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *CICDAdapter) handleGLPipelineFailed(ctx context.Context, p gitlabPipelineEvent) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":      "gitlab_ci",		"project":     p.Project.PathWithNamespace,		"url":         p.ObjectAttributes.URL,		"pipeline_id": p.ObjectAttributes.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *CICDAdapter) handleGLPipelineSuccess(ctx context.Context, p gitlabPipelineEvent) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source":     "github_actions",		"repo":       p.Repository.FullName,		"url":        p.WorkflowRun.HTMLURL,		"conclusion": p.WorkflowRun.Conclusion,		"name":       p.WorkflowRun.Name,		"run_id":     p.WorkflowRun.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *CICDAdapter) handleGHRunFailed(ctx context.Context, p workflowRunEvent) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":  "github_actions",		"repo":    p.Repository.FullName,		"url":     p.WorkflowRun.HTMLURL,		"name":    p.WorkflowRun.Name,		"run_id":  p.WorkflowRun.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *CICDAdapter) handleGHRunSuccess(ctx context.Context, p workflowRunEvent) {}	w.WriteHeader(http.StatusOK)	}		}			a.handleGLPipelineFailed(r.Context(), payload)		case "failed", "canceled":			a.handleGLPipelineSuccess(r.Context(), payload)		case "success":		switch payload.ObjectAttributes.Status {	if payload.ObjectKind == "pipeline" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload gitlabPipelineEvent	}		}			return			http.Error(w, "invalid token", http.StatusUnauthorized)		if r.Header.Get("X-Gitlab-Token") != a.gitlabWebhookSecret {	if a.gitlabWebhookSecret != "" {	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *CICDAdapter) HandleGitLabWebhook(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			}				a.handleGHRunFailed(r.Context(), payload)			case "failure", "cancelled", "timed_out":				a.handleGHRunSuccess(r.Context(), payload)			case "success":			switch payload.WorkflowRun.Conclusion {		if payload.Action == "completed" {	if payload.ObjectKind == "" && r.Header.Get("X-Github-Event") == "workflow_run" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload workflowRunEvent	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *CICDAdapter) HandleGitHubWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8114", mux)	log.Printf("GitHub Actions / GitLab CI adapter listening on :8114")	mux.HandleFunc("/api/v1/runs", adapter.HandleRuns)	mux.HandleFunc("/webhook/gitlab", adapter.HandleGitLabWebhook)	mux.HandleFunc("/webhook/github", adapter.HandleGitHubWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	}		httpClient:          &http.Client{},		bus:                 bus,		gitlabWebhookSecret: os.Getenv("GITLAB_WEBHOOK_SECRET"),		gitlabToken:         os.Getenv("GITLAB_TOKEN"),		githubWebhookSecret: os.Getenv("GITHUB_WEBHOOK_SECRET"),		githubToken:         os.Getenv("GITHUB_TOKEN"),	adapter := &CICDAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")func main() {}	} `json:"project"`		PathWithNamespace string `json:"path_with_namespace"`	Project struct {	} `json:"object_attributes"`		URL    string `json:"url"`		Status string `json:"status"`		ID     int    `json:"id"`	ObjectAttributes struct {	ObjectKind     string `json:"object_kind"`type gitlabPipelineEvent struct {}	} `json:"repository"`		FullName string `json:"full_name"`	Repository struct {	} `json:"workflow_run"`		HTMLURL    string `json:"html_url"`		Conclusion string `json:"conclusion"`		Status     string `json:"status"`		Name       string `json:"name"`		ID         int64  `json:"id"`	WorkflowRun struct {	Action      string `json:"action"`type workflowRunEvent struct {}	httpClient          *http.Client	bus                 events.Bus	gitlabWebhookSecret string	gitlabToken         string	githubWebhookSecret string	githubToken         stringtype CICDAdapter struct {const gitlabAPIBase = "https://gitlab.com/api/v4"const githubAPIBase = "https://api.github.com"// Forge events.// endpoint, distinguishes the source by header, and publishes the appropriate// pipeline events into Forge's message bus. It listens on a single webhook// githubactions adapter bridges GitHub Actions workflow run events and GitLab CI