package mongodbatlas
package main

import (
	"context"
	"crypto/hmac"
	"crypto/sha1"
	"encoding/hex"




























































































































































































































}	return hmac.Equal([]byte(expected), []byte(signature))	expected := "sha1=" + hex.EncodeToString(mac.Sum(nil))	mac.Write(body)	mac := hmac.New(sha1.New, []byte(secret))func validateHMACSHA1(secret string, body []byte, signature string) bool {}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("atlas API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Accept", "application/vnd.atlas.2023-01-01+json")	req.Header.Set("Content-Type", "application/json")	req.SetBasicAuth(a.publicKey, a.privateKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, atlasAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *MongoDBAtlasAdapter) atlasRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	}, func(e events.Event) error {		events.TaskCompleted,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *MongoDBAtlasAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.atlasRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		path := fmt.Sprintf("/groups/%s/clusters", a.projectID)		var result map[string]interface{}	case http.MethodGet:	switch r.Method {func (a *MongoDBAtlasAdapter) HandleClusters(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.atlasRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		path := fmt.Sprintf("/groups/%s/alerts", a.projectID)		var result map[string]interface{}	case http.MethodGet:	switch r.Method {func (a *MongoDBAtlasAdapter) HandleAlerts(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task completed event: %v", err)	}); err != nil {		Payload: eventPayload,		Type:    events.TaskCompleted,	if err := a.bus.Publish(ctx, events.Event{	})		"source":     "mongodbatlas",		"event_type": p.EventType,		"alert_id":   p.ID,	eventPayload, _ := json.Marshal(map[string]interface{}{func (a *MongoDBAtlasAdapter) handleAlertClosed(ctx context.Context, p atlasWebhookPayload) {}	}		log.Printf("failed to publish escalation event: %v", err)	}); err != nil {		Payload: eventPayload,		Type:    events.EscalationCreated,	if err := a.bus.Publish(ctx, events.Event{	})		"source":       "mongodbatlas",		"cluster_name": p.Alert.ClusterName,		"event_type":   p.EventType,		"alert_id":     p.ID,	eventPayload, _ := json.Marshal(map[string]interface{}{func (a *MongoDBAtlasAdapter) handleAlertOpened(ctx context.Context, p atlasWebhookPayload) {}	w.WriteHeader(http.StatusOK)	}		a.handleAlertClosed(r.Context(), payload)	case "ALERT_CLOSED":		a.handleAlertOpened(r.Context(), payload)	case "ALERT_OPENED", "ALERT_CREATED":	switch payload.EventType {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload atlasWebhookPayload	}		}			return			http.Error(w, "invalid signature", http.StatusUnauthorized)		if !validateHMACSHA1(secret, body, sig) {		sig := r.Header.Get("X-MMS-Event-Subscription-Signature")	if secret != "" {	secret := os.Getenv("MONGODB_ATLAS_WEBHOOK_SECRET")	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *MongoDBAtlasAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8106", mux)	log.Printf("MongoDB Atlas adapter listening on :8106")	mux.HandleFunc("/api/v1/clusters", adapter.HandleClusters)	mux.HandleFunc("/api/v1/alerts", adapter.HandleAlerts)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient: &http.Client{},		bus:        bus,		projectID:  os.Getenv("MONGODB_ATLAS_PROJECT_ID"),		privateKey: privateKey,		publicKey:  publicKey,	adapter := &MongoDBAtlasAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("MONGODB_ATLAS_PUBLIC_KEY and MONGODB_ATLAS_PRIVATE_KEY are required")	if publicKey == "" || privateKey == "" {	privateKey := os.Getenv("MONGODB_ATLAS_PRIVATE_KEY")	publicKey := os.Getenv("MONGODB_ATLAS_PUBLIC_KEY")func main() {}	Alert     atlasAlert `json:"alert"`	EventType string     `json:"eventTypeName"`	ID        string     `json:"id"`type atlasWebhookPayload struct {}	ClusterName string `json:"clusterName"`	} `json:"alertConfigId"`		Matchers []interface{} `json:"matchers"`	AlertConfig struct {	Status      string `json:"status"`	EventType   string `json:"eventTypeName"`	ID          string `json:"id"`type atlasAlert struct {}	httpClient *http.Client	bus        events.Bus	projectID  string	privateKey string	publicKey  stringtype MongoDBAtlasAdapter struct {const atlasAPIBase = "https://cloud.mongodb.com/api/atlas/v2")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"