package liquibase
package main

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)
































































































































































































































































}	http.ListenAndServe(":8138", mux)	log.Printf("Liquibase adapter listening on :8138")	mux.HandleFunc("/api/v1/update", adapter.HandleUpdate)	mux.HandleFunc("/api/v1/status", adapter.HandleStatus)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:           bus,		httpClient:    &http.Client{},		webhookSecret: os.Getenv("LIQUIBASE_WEBHOOK_SECRET"),		apiKey:        apiKey,		liquibaseURL:  liquibaseURL,	adapter := &LiquibaseAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("LIQUIBASE_API_KEY is required")	if apiKey == "" {	apiKey := os.Getenv("LIQUIBASE_API_KEY")	}		log.Fatal("LIQUIBASE_URL is required")	if liquibaseURL == "" {	liquibaseURL := os.Getenv("LIQUIBASE_URL")func main() {}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("liquibase API error %d: %s", resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	}		req.Header.Set("X-Liquibase-Api-Key", a.apiKey)	if a.apiKey != "" {	req.Header.Set("Content-Type", "application/json")	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(a.liquibaseURL, "/")+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *LiquibaseAdapter) liquibaseRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// liquibaseRequest is a helper that executes an authenticated call to the Liquibase Pro REST API.}	})		return nil		// Future: parse deployment payload, resolve target database, and call /liquibase/update.	}, func(e events.Event) error {		events.DeploymentRequested,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *LiquibaseAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge deployment requested events and triggers Liquibase updates.}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.WriteHeader(http.StatusCreated)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.liquibaseRequest(r.Context(), http.MethodPost, "/liquibase/update", req, &result); err != nil {		var result liquibaseUpdateResponse		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil && err != io.EOF {		var req liquibaseUpdateRequest	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.liquibaseRequest(r.Context(), http.MethodGet, "/liquibase/status", nil, &result); err != nil {		var result liquibaseStatusResponse	case http.MethodGet:	switch r.Method {func (a *LiquibaseAdapter) HandleUpdate(w http.ResponseWriter, r *http.Request) {// HandleUpdate triggers a Liquibase update (apply pending changesets) via the connected Liquibase Pro API.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.liquibaseRequest(r.Context(), http.MethodGet, "/liquibase/status", nil, &result); err != nil {	var result liquibaseStatusResponse	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *LiquibaseAdapter) HandleStatus(w http.ResponseWriter, r *http.Request) {// HandleStatus returns the current Liquibase changelog status (pending and applied changesets).}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task failed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskFailed,		if err := a.bus.Publish(r.Context(), events.Event{		eventPayload, _ = json.Marshal(base)		base["reason"] = fmt.Sprintf("Liquibase %s failed for database %s in project %s: %s", payload.Event, payload.Database, payload.Project, payload.Message)	case payload.Event == "update.failed" || payload.Event == "rollback.failed":		}			log.Printf("failed to publish task completed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskCompleted,		if err := a.bus.Publish(r.Context(), events.Event{	case payload.Event == "update.success" || payload.Event == "rollback.success":	switch {	eventPayload, _ := json.Marshal(base)	}		"message":     payload.Message,		"changeCount": payload.ChangeCount,		"database":    payload.Database,		"environment": payload.Environment,		"project":     payload.Project,		"event":       payload.Event,		"source":      "liquibase",	base := map[string]interface{}{	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload liquibaseWebhookPayload	}		return		http.Error(w, "invalid signature", http.StatusUnauthorized)	if !a.verifySignature(r, body) {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *LiquibaseAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound Liquibase Pro event notifications.}	return hmac.Equal([]byte(sig), []byte(expected))	expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))	mac.Write(body)	mac := hmac.New(sha256.New, []byte(a.webhookSecret))	}		return false	if sig == "" {	sig := r.Header.Get("X-Liquibase-Signature")	}		return true	if a.webhookSecret == "" {func (a *LiquibaseAdapter) verifySignature(r *http.Request, body []byte) bool {// verifySignature validates the Liquibase webhook HMAC-SHA256 signature.}	Message           string `json:"message,omitempty"`	Success           bool   `json:"success"`	ChangesetsApplied int    `json:"changesetsApplied"`type liquibaseUpdateResponse struct {// liquibaseUpdateResponse is returned after a successful update API call.}	Labels      string `json:"labels,omitempty"`	Contexts    string `json:"contexts,omitempty"`	ChangelogFile string `json:"changelogFile,omitempty"`	Tag         string `json:"tag,omitempty"`         // apply up to this tag; blank means apply all pendingtype liquibaseUpdateRequest struct {// liquibaseUpdateRequest is the body for triggering a Liquibase update operation via the API.}	Applied         []liquibaseChangesetStatus `json:"applied"`	Pending         []liquibaseChangesetStatus `json:"pending"`	DatabaseVersion string                     `json:"databaseVersion"`type liquibaseStatusResponse struct {// liquibaseStatusResponse wraps the list of changeset status records from /liquibase/status.}	MD5Sum        string `json:"md5Sum"`	OrderExecuted int    `json:"orderExecuted,omitempty"`	DateExecuted  string `json:"dateExecuted,omitempty"`	ExecType      string `json:"execType"`	DeploymentID  string `json:"deploymentId,omitempty"`	Filename      string `json:"filename"`	Author        string `json:"author"`	ID            string `json:"id"`type liquibaseChangesetStatus struct {// liquibaseChangesetStatus represents a single changeset row from Liquibase's status response.}	} `json:"changesets"`		State    string `json:"state"` // EXECUTED, FAILED, SKIPPED		Filename string `json:"filename"`		Author   string `json:"author"`		ID       string `json:"id"`	Changesets  []struct {	Message     string `json:"message"`	ChangeCount int    `json:"changeCount"`	Database    string `json:"database"`	Environment string `json:"environment"`	Project     string `json:"project"`	Event       string `json:"event"`        // update.success, update.failed, rollback.success, rollback.failedtype liquibaseWebhookPayload struct {// liquibaseWebhookPayload is the envelope Liquibase sends to configured webhook URLs on changelog events.}	bus           events.Bus	httpClient    *http.Client	webhookSecret string	apiKey        string	liquibaseURL  stringtype LiquibaseAdapter struct {// LiquibaseAdapter bridges Liquibase Pro changelog events with the Forge event bus.