package atlantis
package main

import (
	"bytes"
	"context"










































































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("atlantis API error %d: %s", resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("X-Atlantis-Token", a.token)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, a.atlantisURL+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *AtlantisAdapter) atlantisRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// atlantisRequest is a helper that executes an authenticated Atlantis API call.}	})		return nil		// Future: extract repo/workspace from payload and call atlantis apply.	}, func(e events.Event) error {		events.DeploymentApproved,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *AtlantisAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge deployment approval events and triggers Atlantis applies.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.atlantisRequest(r.Context(), http.MethodPost, "/api/v1/apply", req, &result); err != nil {	var result map[string]interface{}	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req atlantisApplyRequest	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AtlantisAdapter) HandleApply(w http.ResponseWriter, r *http.Request) {// HandleApply triggers an Atlantis apply operation.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.atlantisRequest(r.Context(), http.MethodPost, "/api/v1/plan", req, &result); err != nil {	var result map[string]interface{}	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	var req atlantisPlanRequest	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AtlantisAdapter) HandlePlan(w http.ResponseWriter, r *http.Request) {// HandlePlan triggers an Atlantis plan operation.}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task failed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskFailed,		if err := a.bus.Publish(r.Context(), events.Event{		eventPayload, _ := json.Marshal(base)		base["reason"] = fmt.Sprintf("Atlantis %s %s failed for %s", payload.Stage, payload.Operation, payload.Repo.FullName)	case payload.Status == "failure" || payload.Status == "error":		}			log.Printf("failed to publish deployment requested event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.DeploymentRequested,		if err := a.bus.Publish(r.Context(), events.Event{		eventPayload, _ := json.Marshal(base)	case payload.Stage == "plan" && payload.Status == "success":		}			log.Printf("failed to publish task completed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskCompleted,		if err := a.bus.Publish(r.Context(), events.Event{		eventPayload, _ := json.Marshal(base)	case payload.Stage == "apply" && payload.Status == "success":	switch {	}		base["branch"] = payload.Pull.Branch		base["pr_number"] = payload.Pull.Num	if payload.Pull != nil {	}		"status":    payload.Status,		"operation": payload.Operation,		"stage":     payload.Stage,		"repo":      payload.Repo.FullName,		"source":    "atlantis",	base := map[string]interface{}{	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload atlantisWebhookPayload	}		return		http.Error(w, "invalid signature", http.StatusUnauthorized)	if !a.verifySignature(r, body) {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *AtlantisAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound Atlantis event notifications.}	return hmac.Equal([]byte(sig), []byte(expected))	expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))	mac.Write(body)	mac := hmac.New(sha256.New, []byte(a.webhookSecret))	}		return false	if sig == "" {	sig := r.Header.Get("X-Atlantis-Signature")	}		return true	if a.webhookSecret == "" {func (a *AtlantisAdapter) verifySignature(r *http.Request, body []byte) bool {// verifySignature validates the Atlantis webhook HMAC-SHA256 signature.}	http.ListenAndServe(":8105", mux)	log.Printf("Atlantis adapter listening on :8105")	mux.HandleFunc("/api/v1/apply", adapter.HandleApply)	mux.HandleFunc("/api/v1/plan", adapter.HandlePlan)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:           bus,		httpClient:    &http.Client{},		webhookSecret: os.Getenv("ATLANTIS_WEBHOOK_SECRET"),		token:         token,		atlantisURL:   strings.TrimRight(atlantisURL, "/"),	adapter := &AtlantisAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("ATLANTIS_TOKEN is required")	if token == "" {	token := os.Getenv("ATLANTIS_TOKEN")	}		log.Fatal("ATLANTIS_URL is required")	if atlantisURL == "" {	atlantisURL := os.Getenv("ATLANTIS_URL")func main() {}	Message string `json:"message"`	Success bool   `json:"success"`type atlantisLockResponse struct {// atlantisLockResponse is returned when locking a project.}	RepoRelDir string `json:"repoRelDir"`	Workspace  string `json:"workspace"`	Branch     string `json:"branch"`	Repo       string `json:"repo"`type atlantisApplyRequest struct {// atlantisApplyRequest triggers an Atlantis apply via the API.}	Verbose    bool   `json:"verbose"`	RepoRelDir string `json:"repoRelDir"`	Workspace  string `json:"workspace"`	Branch     string `json:"branch"`	Repo       string `json:"repo"`type atlantisPlanRequest struct {// atlantisPlanRequest triggers an Atlantis plan via the API.}	} `json:"projectResults"`		} `json:"failure,omitempty"`			Error string `json:"error"`		Failure *struct {		} `json:"applySuccess,omitempty"`			TerraformOutput string `json:"terraformOutput"`		ApplySuccess *struct {		} `json:"planSuccess,omitempty"`			NumDestructions int    `json:"numDestructions"`			NumChanges      int    `json:"numChanges"`			NumAdditions    int    `json:"numAdditions"`			TerraformOutput string `json:"terraformOutput"`		PlanSuccess   *struct {		Status        string `json:"status"`		RepoRelDir    string `json:"repoRelDir"`		Workspace     string `json:"workspace"`		ProjectName   string `json:"projectName"`	ProjectResults []struct {	Log           string `json:"log"`	HeadCommit    string `json:"head_commit"`	} `json:"pull"`		Author string `json:"author"`		Branch string `json:"branch"`		Num    int    `json:"num"`	Pull *struct {	} `json:"repo"`		FullName string `json:"full_name"`	Repo      struct {	Status    string `json:"status"`      // success, failure, error	Operation string `json:"operation"`   // plan, apply, destroy	Stage     string `json:"stage"`       // plan, applytype atlantisWebhookPayload struct {// atlantisWebhookPayload is the payload Atlantis sends to configured webhook URLs.}	bus           events.Bus	httpClient    *http.Client	webhookSecret string	token         string	atlantisURL   stringtype AtlantisAdapter struct {// AtlantisAdapter bridges Atlantis Terraform automation events with the Forge event bus.)	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"	"encoding/hex"	"crypto/sha256"	"crypto/hmac"