package circleci
package main

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"



















































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("circleci API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Circle-Token", a.token)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, circleAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *CircleCIAdapter) circleRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentRequested}, func(e events.Event) error {	ctx := context.Background()func (a *CircleCIAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.circleRequest(r.Context(), http.MethodGet, fmt.Sprintf("/pipeline/%s/workflow", pipelineID), nil, &result); err != nil {		var result map[string]interface{}		}			return			http.Error(w, "pipeline_id query parameter is required", http.StatusBadRequest)		if pipelineID == "" {		pipelineID := r.URL.Query().Get("pipeline_id")	case http.MethodGet:	switch r.Method {func (a *CircleCIAdapter) HandleWorkflows(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.circleRequest(r.Context(), http.MethodGet, fmt.Sprintf("/project/%s/pipeline", projectSlug), nil, &result); err != nil {		var result map[string]interface{}		}			return			http.Error(w, "project_slug query parameter is required", http.StatusBadRequest)		if projectSlug == "" {		projectSlug := r.URL.Query().Get("project_slug")	case http.MethodGet:	switch r.Method {func (a *CircleCIAdapter) HandlePipelines(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source":        "circleci",		"project":       p.Pipeline.ProjectSlug,		"pipeline_id":   p.Pipeline.ID,		"status":        p.Workflow.Status,		"workflow_name": p.Workflow.Name,		"workflow_id":   p.Workflow.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *CircleCIAdapter) handleWorkflowFailed(ctx context.Context, p circleCIWebhookPayload) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":        "circleci",		"project":       p.Pipeline.ProjectSlug,		"pipeline_id":   p.Pipeline.ID,		"workflow_name": p.Workflow.Name,		"workflow_id":   p.Workflow.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *CircleCIAdapter) handleWorkflowSuccess(ctx context.Context, p circleCIWebhookPayload) {}	w.WriteHeader(http.StatusOK)	}		}			a.handleWorkflowFailed(r.Context(), payload)		case "failed", "error", "canceled", "unauthorized":			a.handleWorkflowSuccess(r.Context(), payload)		case "success":		switch payload.Workflow.Status {	if payload.Type == "workflow-completed" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload circleCIWebhookPayload	}		}			return			http.Error(w, "invalid signature", http.StatusUnauthorized)		if !hmac.Equal([]byte(expected), []byte(sig)) {		expected := "v1=" + hex.EncodeToString(mac.Sum(nil))		mac.Write(body)		mac := hmac.New(sha256.New, []byte(a.webhookSecret))		sig := r.Header.Get("Circleci-Signature")	if a.webhookSecret != "" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *CircleCIAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8112", mux)	log.Printf("CircleCI adapter listening on :8112")	mux.HandleFunc("/api/v1/workflows", adapter.HandleWorkflows)	mux.HandleFunc("/api/v1/pipelines", adapter.HandlePipelines)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:    &http.Client{},		bus:           bus,		webhookSecret: os.Getenv("CIRCLECI_WEBHOOK_SECRET"),		token:         token,	adapter := &CircleCIAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("CIRCLECI_TOKEN is required")	if token == "" {	token := os.Getenv("CIRCLECI_TOKEN")func main() {}	Pipeline circleCIPipeline `json:"pipeline"`	Workflow circleCIWorkflow `json:"workflow"`	Type     string           `json:"type"`type circleCIWebhookPayload struct {}	ProjectSlug string `json:"project_slug"`	ID         string `json:"id"`type circleCIPipeline struct {}	Status string `json:"status"`	Name   string `json:"name"`	ID     string `json:"id"`type circleCIWorkflow struct {}	httpClient    *http.Client	bus           events.Bus	webhookSecret string	token         stringtype CircleCIAdapter struct {const circleAPIBase = "https://circleci.com/api/v2")	"github.com/dotrage/forge-adp/pkg/events"