package vercel
package main

import (
	"context"
	"crypto/hmac"


































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("vercel API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "Bearer "+a.token)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, vercelAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *VercelAdapter) vercelRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.DeploymentRequested}, func(e events.Event) error {	ctx := context.Background()func (a *VercelAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.vercelRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result map[string]interface{}		}			path += "?teamId=" + a.teamID		if a.teamID != "" {		path := "/v9/projects"	case http.MethodGet:	switch r.Method {func (a *VercelAdapter) HandleProjects(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.vercelRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result map[string]interface{}		}			path += "?teamId=" + a.teamID		if a.teamID != "" {		path := "/v6/deployments"	case http.MethodGet:	switch r.Method {func (a *VercelAdapter) HandleDeployments(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task failed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskFailed, Payload: ep}); err != nil {	})		"source":        "vercel",		"state":         d.State,		"name":          d.Name,		"deployment_id": d.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *VercelAdapter) handleDeploymentFailed(ctx context.Context, d vercelDeployment) {}	}		log.Printf("failed to publish deployment approved event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.DeploymentApproved, Payload: ep}); err != nil {	})		"source":        "vercel",		"url":           d.URL,		"name":          d.Name,		"deployment_id": d.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *VercelAdapter) handleDeploymentReady(ctx context.Context, d vercelDeployment) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":        "vercel",		"state":         d.State,		"url":           d.URL,		"name":          d.Name,		"deployment_id": d.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *VercelAdapter) handleDeploymentSucceeded(ctx context.Context, d vercelDeployment) {}	w.WriteHeader(http.StatusOK)	}		a.handleDeploymentReady(r.Context(), payload.Payload)	case "deployment.ready":		a.handleDeploymentFailed(r.Context(), payload.Payload)	case "deployment.error", "deployment.canceled":		a.handleDeploymentSucceeded(r.Context(), payload.Payload)	case "deployment.succeeded":	switch payload.Type {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload vercelWebhookPayload	}		}			return			http.Error(w, "invalid signature", http.StatusUnauthorized)		if !hmac.Equal([]byte(expected), []byte(sig)) {		expected := hex.EncodeToString(mac.Sum(nil))		mac.Write(body)		mac := hmac.New(sha1.New, []byte(a.webhookSecret))		sig := r.Header.Get("X-Vercel-Signature")	if a.webhookSecret != "" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *VercelAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8108", mux)	log.Printf("Vercel adapter listening on :8108")	mux.HandleFunc("/api/v1/projects", adapter.HandleProjects)	mux.HandleFunc("/api/v1/deployments", adapter.HandleDeployments)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:    &http.Client{},		bus:           bus,		webhookSecret: os.Getenv("VERCEL_WEBHOOK_SECRET"),		teamID:        os.Getenv("VERCEL_TEAM_ID"),		token:         token,	adapter := &VercelAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("VERCEL_TOKEN is required")	if token == "" {	token := os.Getenv("VERCEL_TOKEN")func main() {}	Payload    vercelDeployment `json:"payload"`	Type       string           `json:"type"`type vercelWebhookPayload struct {}	Meta  map[string]string `json:"meta"`	State string `json:"state"`	URL   string `json:"url"`	Name  string `json:"name"`	ID    string `json:"id"`type vercelDeployment struct {}	httpClient *http.Client	bus        events.Bus	webhookSecret string	teamID     string	token      stringtype VercelAdapter struct {const vercelAPIBase = "https://api.vercel.com")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"	"encoding/hex"	"crypto/sha1"