package testrail
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"











































































































































































































































var _ = xrayAPIBase// client credentials — token exchange omitted here for brevity.// xrayAPIBase is referenced for completeness; Xray Cloud auth uses OAuth2}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("testrail API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.SetBasicAuth(a.testRailUser, a.testRailAPIKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, a.testRailURL+testRailAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Reader	}		return fmt.Errorf("TESTRAIL_URL not configured")	if a.testRailURL == "" {func (a *TestRailAdapter) trRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.ReviewApproved}, func(e events.Event) error {	ctx := context.Background()func (a *TestRailAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.trRequest(r.Context(), http.MethodGet, fmt.Sprintf("/get_results_for_run/%s", runID), nil, &result); err != nil {		var result interface{}		}			return			http.Error(w, "run_id query parameter is required", http.StatusBadRequest)		if runID == "" {		runID := r.URL.Query().Get("run_id")	case http.MethodGet:	switch r.Method {func (a *TestRailAdapter) HandleResults(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.trRequest(r.Context(), http.MethodGet, fmt.Sprintf("/get_runs/%s", projectID), nil, &result); err != nil {		var result interface{}		}			return			http.Error(w, "project_id query parameter is required", http.StatusBadRequest)		if projectID == "" {		projectID := r.URL.Query().Get("project_id")	case http.MethodGet:	switch r.Method {func (a *TestRailAdapter) HandleRuns(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})		})			"source":   "xray",			"exec_key": result.TestExecKey,		ep, _ := json.Marshal(map[string]interface{}{	} else if result.Status == "PASS" {		a.bus.Publish(r.Context(), events.Event{Type: events.TaskBlocked, Payload: ep})		})			"source":   "xray",			"failed":   failedCount,			"exec_key": result.TestExecKey,		ep, _ := json.Marshal(map[string]interface{}{	if failedCount > 0 {	}		}			failedCount++		if t.Status == "FAIL" {	for _, t := range result.Tests {	failedCount := 0	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&result); err != nil {	var result xraylTestExecutionResult	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *TestRailAdapter) HandleXrayWebhook(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})			})				"source":   "testrail",				"passed":   payload.Payload.PassedCount,				"run_name": payload.Payload.Name,				"run_id":   payload.Payload.ID,			ep, _ := json.Marshal(map[string]interface{}{		} else {			a.bus.Publish(r.Context(), events.Event{Type: events.TaskBlocked, Payload: ep})			})				"source":   "testrail",				"passed":   payload.Payload.PassedCount,				"failed":   payload.Payload.FailedCount,				"run_name": payload.Payload.Name,				"run_id":   payload.Payload.ID,			ep, _ := json.Marshal(map[string]interface{}{		if payload.Payload.FailedCount > 0 {	if payload.Name == "close_run" && payload.Payload.IsCompleted {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload testRailWebhookPayload	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *TestRailAdapter) HandleTestRailWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8130", mux)	log.Printf("TestRail / Xray adapter listening on :8130")	mux.HandleFunc("/api/v1/results", adapter.HandleResults)	mux.HandleFunc("/api/v1/runs", adapter.HandleRuns)	mux.HandleFunc("/webhook/xray", adapter.HandleXrayWebhook)	mux.HandleFunc("/webhook/testrail", adapter.HandleTestRailWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:      &http.Client{},		bus:             bus,		xrayClientSecret: os.Getenv("XRAY_CLIENT_SECRET"),		xrayClientID:    os.Getenv("XRAY_CLIENT_ID"),		testRailAPIKey:  os.Getenv("TESTRAIL_API_KEY"),		testRailUser:    os.Getenv("TESTRAIL_USER"),		testRailURL:     strings.TrimRight(os.Getenv("TESTRAIL_URL"), "/"),	adapter := &TestRailAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")func main() {}	} `json:"tests"`		TestKey string `json:"testKey"`		Status  string `json:"status"`	Tests       []struct {	Status      string `json:"status"`	TestExecKey string `json:"testExecKey"`type xraylTestExecutionResult struct {}	Payload testRailRun `json:"payload"`	Name    string      `json:"name"`type testRailWebhookPayload struct {}	IsCompleted     bool   `json:"is_completed"`	UntestedCount   int    `json:"untested_count"`	FailedCount     int    `json:"failed_count"`	PassedCount     int    `json:"passed_count"`	Description     string `json:"description"`	Name            string `json:"name"`	ID              int    `json:"id"`type testRailRun struct {}	httpClient      *http.Client	bus             events.Bus	xrayClientSecret string	xrayClientID    string	testRailAPIKey  string	testRailUser    string	testRailURL     stringtype TestRailAdapter struct {const xrayAPIBase = "https://xray.cloud.getxray.app/api/v2"const testRailAPIBase = "/index.php?/api/v2"// both services route test run outcomes to Forge's message bus.// management and Xray (Jira plugin) for test execution results. Webhooks from// TestRail / Xray adapter integrates with TestRail's API for test case)