package postman
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)

// Postman / Newman adapter integrates with Postman's Cloud API and receives
// monitor failure webhooks. It also supports triggering collection runs via
// the Postman API and parsing Newman JSON reports pushed via webhook.
































































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("postman API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("X-Api-Key", a.apiKey)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, postmanAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *PostmanAdapter) pmRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.ReviewApproved}, func(e events.Event) error {	ctx := context.Background()func (a *PostmanAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.WriteHeader(http.StatusCreated)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.pmRequest(r.Context(), http.MethodPost, "/collections/"+body.CollectionID+"/runs", payload, &result); err != nil {		var result interface{}		}			payload["environment"] = body.EnvironmentID		if body.EnvironmentID != "" {		}			"collection": body.CollectionID,		payload := map[string]interface{}{		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {		}			EnvironmentID string `json:"environment_id,omitempty"`			CollectionID string `json:"collection_id"`		var body struct {		// Trigger a collection run via Postman Cloud	case http.MethodPost:	switch r.Method {func (a *PostmanAdapter) HandleRuns(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.pmRequest(r.Context(), http.MethodGet, "/monitors", nil, &result); err != nil {		var result interface{}	case http.MethodGet:	switch r.Method {func (a *PostmanAdapter) HandleMonitors(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.pmRequest(r.Context(), http.MethodGet, "/collections", nil, &result); err != nil {		var result interface{}	case http.MethodGet:	switch r.Method {func (a *PostmanAdapter) HandleCollections(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})		})			"source":       "newman",			"total_passed": report.Run.Stats.Assertions.Total,			"collection":   report.Run.Collection.Info.Name,		ep, _ := json.Marshal(map[string]interface{}{	} else {		a.bus.Publish(r.Context(), events.Event{Type: events.TaskBlocked, Payload: ep})		})			"source":            "newman",			"failures":          report.Run.Failures,			"total_assertions":  report.Run.Stats.Assertions.Total,			"failed_assertions": report.Run.Stats.Assertions.Failed,			"collection":        report.Run.Collection.Info.Name,		ep, _ := json.Marshal(map[string]interface{}{	if report.Run.Stats.Assertions.Failed > 0 {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&report); err != nil {	var report newmanReport	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *PostmanAdapter) HandleNewmanWebhook(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep})		})			"source":       "postman",			"total_passed": payload.Run.Stats.Assertions.Total,			"monitor_name": payload.Monitor.Name,			"monitor_id":   payload.Monitor.ID,		ep, _ := json.Marshal(map[string]interface{}{	case "passed":		a.bus.Publish(r.Context(), events.Event{Type: events.EscalationCreated, Payload: ep})		})			"source":             "postman",			"failure_count":      len(payload.Run.Failures),			"total_assertions":   payload.Run.Stats.Assertions.Total,			"failed_assertions":  payload.Run.Stats.Assertions.Failed,			"monitor_name":       payload.Monitor.Name,			"monitor_id":         payload.Monitor.ID,		ep, _ := json.Marshal(map[string]interface{}{	case "failed":	switch payload.Run.Status {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload postmanMonitorWebhook	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *PostmanAdapter) HandleMonitorWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8133", mux)	log.Printf("Postman / Newman adapter listening on :8133")	mux.HandleFunc("/api/v1/runs", adapter.HandleRuns)	mux.HandleFunc("/api/v1/monitors", adapter.HandleMonitors)	mux.HandleFunc("/api/v1/collections", adapter.HandleCollections)	mux.HandleFunc("/webhook/newman", adapter.HandleNewmanWebhook)	mux.HandleFunc("/webhook/monitor", adapter.HandleMonitorWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient: &http.Client{},		bus:        bus,		apiKey:     os.Getenv("POSTMAN_API_KEY"),	adapter := &PostmanAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")func main() {}	} `json:"run"`		} `json:"failures"`			Source struct{ Name string }   `json:"source"`			Error  struct{ Message string } `json:"error"`		Failures []struct {		} `json:"collection"`			} `json:"info"`				Name string `json:"name"`			Info struct {		Collection struct {		} `json:"stats"`			} `json:"assertions"`				Failed int `json:"failed"`				Total  int `json:"total"`			Assertions struct {		Stats struct {	Run struct {type newmanReport struct {}	} `json:"run"`		} `json:"failures"`			} `json:"error"`				Message string `json:"message"`			Error struct {			} `json:"source"`				Name string `json:"name"`			Source struct {		Failures []struct {		} `json:"stats"`			} `json:"requests"`				Failed int `json:"failed"`				Total  int `json:"total"`			Requests struct {			} `json:"assertions"`				Failed int `json:"failed"`				Total  int `json:"total"`			Assertions struct {		Stats  struct {		Status string `json:"status"` // "passed" | "failed"	Run struct {	} `json:"monitor"`		Name string `json:"name"`		ID   string `json:"id"`	Monitor struct {type postmanMonitorWebhook struct {}	httpClient *http.Client	bus        events.Bus	apiKey     stringtype PostmanAdapter struct {const postmanAPIBase = "https://api.getpostman.com"