package flyway
package main

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"


























































































































































































































































}	http.ListenAndServe(":8137", mux)	log.Printf("Flyway adapter listening on :8137")	mux.HandleFunc("/api/v1/migrate", adapter.HandleMigrate)	mux.HandleFunc("/api/v1/info", adapter.HandleInfo)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		bus:           bus,		httpClient:    &http.Client{},		webhookSecret: os.Getenv("FLYWAY_WEBHOOK_SECRET"),		token:         token,		flywayURL:     flywayURL,	adapter := &FlywayAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	token := os.Getenv("FLYWAY_TOKEN")	}		log.Fatal("FLYWAY_URL is required")	if flywayURL == "" {	flywayURL := os.Getenv("FLYWAY_URL")func main() {}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("flyway API error %d: %s", resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	}		req.Header.Set("Authorization", "Bearer "+a.token)	if a.token != "" {	req.Header.Set("Content-Type", "application/json")	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(a.flywayURL, "/")+path, bodyReader)	}		bodyReader = bytes.NewReader(b)		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *FlywayAdapter) flywayRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {// flywayRequest is a helper that executes an authenticated call to the Flyway server REST API.}	})		return nil		// Future: parse deployment payload, resolve target schema, and call /flyway/migrate.	}, func(e events.Event) error {		events.DeploymentRequested,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *FlywayAdapter) subscribeToEvents() {// subscribeToEvents listens for Forge deployment requested events and triggers Flyway migrations.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.flywayRequest(r.Context(), http.MethodPost, "/flyway/migrate", req, &result); err != nil {	var result flywayMigrateResponse	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil && err != io.EOF {	var req flywayMigrateRequest	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *FlywayAdapter) HandleMigrate(w http.ResponseWriter, r *http.Request) {// HandleMigrate triggers a Flyway migration via the connected Flyway server's REST endpoint.}	json.NewEncoder(w).Encode(result)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)	if err := a.flywayRequest(r.Context(), http.MethodGet, "/flyway/info", nil, &result); err != nil {	var result flywayInfoResponse	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (a *FlywayAdapter) HandleInfo(w http.ResponseWriter, r *http.Request) {// HandleInfo returns the current Flyway migration state from the connected Flyway server.}	w.WriteHeader(http.StatusOK)	}		}			log.Printf("failed to publish task failed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskFailed,		if err := a.bus.Publish(r.Context(), events.Event{		eventPayload, _ = json.Marshal(base)		base["reason"] = fmt.Sprintf("Flyway migration failed for schema %s on %s: %s", payload.Schema, payload.Environment, payload.Message)	case payload.Event == "migration.failed" || payload.Event == "validate.failed":		}			log.Printf("failed to publish task completed event: %v", err)		}); err != nil {			Payload: eventPayload,			Type:    events.TaskCompleted,		if err := a.bus.Publish(r.Context(), events.Event{	case payload.Event == "migration.success":	switch {	eventPayload, _ := json.Marshal(base)	}		"message":     payload.Message,		"migrated":    payload.Migrated,		"schema":      payload.Schema,		"environment": payload.Environment,		"event":       payload.Event,		"source":      "flyway",	base := map[string]interface{}{	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload flywayWebhookPayload	}		return		http.Error(w, "invalid signature", http.StatusUnauthorized)	if !a.verifySignature(r, body) {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *FlywayAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// HandleWebhook processes inbound Flyway event notifications.}	return hmac.Equal([]byte(sig), []byte(expected))	expected := "sha256=" + hex.EncodeToString(mac.Sum(nil))	mac.Write(body)	mac := hmac.New(sha256.New, []byte(a.webhookSecret))	}		return false	if sig == "" {	sig := r.Header.Get("X-Flyway-Signature")	}		return true	if a.webhookSecret == "" {func (a *FlywayAdapter) verifySignature(r *http.Request, body []byte) bool {// verifySignature validates the Flyway webhook HMAC-SHA256 signature.}	Message            string `json:"message,omitempty"`	Success            bool   `json:"success"`	MigrationsExecuted int    `json:"migrationsExecuted"`type flywayMigrateResponse struct {// flywayMigrateResponse is returned after a successful migration API call.}	Schemas     []string `json:"schemas,omitempty"`	OutOfOrder  bool   `json:"outOfOrder,omitempty"`	Target      string `json:"target,omitempty"`      // target version; blank means latesttype flywayMigrateRequest struct {// flywayMigrateRequest is the optional body for triggering a Flyway migration via the API.}	Migrations    []flywayMigrationInfo `json:"migrations"`	SchemaVersion string                `json:"schemaVersion"`type flywayInfoResponse struct {// flywayInfoResponse wraps the list of migration info records from /flyway/info.}	ExecutionTime  int    `json:"executionTime,omitempty"` // milliseconds	InstalledOn    string `json:"installedOn,omitempty"`	State          string `json:"state"`	Script         string `json:"script"`	Type           string `json:"type"`	Description    string `json:"description"`	Version        string `json:"version"`type flywayMigrationInfo struct {// flywayMigrationInfo represents a single row from Flyway's migration history.}	} `json:"migrations"`		State       string `json:"state"` // Success, Failed		Script      string `json:"script"`		Type        string `json:"type"`		Description string `json:"description"`		Version     string `json:"version"`	Migrations  []struct {	Message     string `json:"message"`	Migrated    int    `json:"migrated"`     // number of migrations applied	Schema      string `json:"schema"`       // target schema/database	Environment string `json:"environment"`  // target environment name	Event       string `json:"event"`        // migration.success, migration.failed, validate.failedtype flywayWebhookPayload struct {// flywayWebhookPayload is the envelope Flyway sends to configured webhook URLs on migration events.}	bus           events.Bus	httpClient    *http.Client	webhookSecret string	token         string	flywayURL     stringtype FlywayAdapter struct {// FlywayAdapter bridges Flyway Teams/Enterprise migration events with the Forge event bus.)	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"	"encoding/hex"