package sentry
package main

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"























































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("sentry API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Authorization", "Bearer "+a.authToken)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, sentryAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *SentryAdapter) sentryRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	a.bus.Subscribe(ctx, []events.EventType{events.TaskCompleted}, func(e events.Event) error {	ctx := context.Background()func (a *SentryAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.sentryRequest(r.Context(), http.MethodGet, fmt.Sprintf("/organizations/%s/projects/", a.orgSlug), nil, &result); err != nil {		var result interface{}	case http.MethodGet:	switch r.Method {func (a *SentryAdapter) HandleProjects(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.sentryRequest(r.Context(), http.MethodGet, path, nil, &result); err != nil {		var result interface{}		}			path += "?project=" + project		if project != "" {		path := fmt.Sprintf("/organizations/%s/issues/", a.orgSlug)		project := r.URL.Query().Get("project")	case http.MethodGet:	switch r.Method {func (a *SentryAdapter) HandleIssues(w http.ResponseWriter, r *http.Request) {}	}		log.Printf("failed to publish task completed event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {	})		"source":   "sentry",		"project":  issue.Project.Slug,		"title":    issue.Title,		"issue_id": issue.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *SentryAdapter) handleIssueResolved(ctx context.Context, issue sentryIssue) {}	}		log.Printf("failed to publish escalation event: %v", err)	if err := a.bus.Publish(ctx, events.Event{Type: events.EscalationCreated, Payload: ep}); err != nil {	})		"source":    "sentry",		"url":       issue.Permalink,		"project":   issue.Project.Slug,		"level":     issue.Level,		"title":     issue.Title,		"issue_id":  issue.ID,	ep, _ := json.Marshal(map[string]interface{}{func (a *SentryAdapter) handleIssueCreated(ctx context.Context, issue sentryIssue) {}	w.WriteHeader(http.StatusOK)	}		a.handleIssueResolved(r.Context(), payload.Data.Issue)	case "resolved":		}			a.handleIssueCreated(r.Context(), payload.Data.Issue)		if payload.Data.Issue.Level == "error" || payload.Data.Issue.Level == "fatal" {	case "created":	switch payload.Action {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.Unmarshal(body, &payload); err != nil {	var payload sentryWebhookPayload	}		}			return			http.Error(w, "invalid signature", http.StatusUnauthorized)		if !hmac.Equal([]byte(expected), []byte(sig)) {		expected := hex.EncodeToString(mac.Sum(nil))		mac.Write(body)		mac := hmac.New(sha256.New, []byte(a.webhookSecret))		sig := r.Header.Get("Sentry-Hook-Signature")	if a.webhookSecret != "" {	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err != nil {	body, err := io.ReadAll(r.Body)	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *SentryAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {}	http.ListenAndServe(":8115", mux)	log.Printf("Sentry adapter listening on :8115")	mux.HandleFunc("/api/v1/projects", adapter.HandleProjects)	mux.HandleFunc("/api/v1/issues", adapter.HandleIssues)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:    &http.Client{},		bus:           bus,		webhookSecret: os.Getenv("SENTRY_WEBHOOK_SECRET"),		orgSlug:       os.Getenv("SENTRY_ORG_SLUG"),		authToken:     authToken,	adapter := &SentryAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("SENTRY_AUTH_TOKEN is required")	if authToken == "" {	authToken := os.Getenv("SENTRY_AUTH_TOKEN")func main() {}	} `json:"data"`		Issue sentryIssue `json:"issue"`	Data   struct {	Action string      `json:"action"`type sentryWebhookPayload struct {}	} `json:"project"`		Slug string `json:"slug"`	Project     struct {	Permalink   string `json:"permalink"`	Status      string `json:"status"`	Level       string `json:"level"`	Title       string `json:"title"`	ID          string `json:"id"`type sentryIssue struct {}	httpClient    *http.Client	bus           events.Bus	webhookSecret string	orgSlug       string	authToken     stringtype SentryAdapter struct {const sentryAPIBase = "https://sentry.io/api/0")	"github.com/dotrage/forge-adp/pkg/events"	"strings"	"os"	"net/http"	"log"	"io"	"fmt"	"encoding/json"