package notion
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/dotrage/forge-adp/pkg/events"
)

const notionAPIBase = "https://api.notion.com/v1"
const notionVersion = "2022-06-28"







































































































































































































































}	return nil	}		}			return fmt.Errorf("decode response: %w", err)		if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	if out != nil {	}		return fmt.Errorf("notion API error %d: %s", resp.StatusCode, string(b))		b, _ := io.ReadAll(resp.Body)	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return fmt.Errorf("execute request: %w", err)	if err != nil {	resp, err := a.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	req.Header.Set("Notion-Version", notionVersion)	req.Header.Set("Authorization", "Bearer "+a.token)	}		return fmt.Errorf("create request: %w", err)	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, notionAPIBase+path, bodyReader)	}		bodyReader = strings.NewReader(string(b))		}			return fmt.Errorf("marshal request: %w", err)		if err != nil {		b, err := json.Marshal(body)	if body != nil {	var bodyReader io.Readerfunc (a *NotionAdapter) notionRequest(ctx context.Context, method, path string, body interface{}, out interface{}) error {}	})		return nil	}, func(e events.Event) error {		events.TaskFailed,		events.TaskCompleted,	a.bus.Subscribe(ctx, []events.EventType{	ctx := context.Background()func (a *NotionAdapter) subscribeToEvents() {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.notionRequest(r.Context(), http.MethodPost, fmt.Sprintf("/databases/%s/query", id), req, &result); err != nil {		var result map[string]interface{}		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req map[string]interface{}		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if id == "" {		}			id = a.databaseID		if id == "" && a.databaseID != "" {		id := r.URL.Query().Get("id")	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.notionRequest(r.Context(), http.MethodGet, "/databases/"+id, nil, &result); err != nil {		var result map[string]interface{}		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if id == "" {		}			id = a.databaseID		if id == "" && a.databaseID != "" {		id := r.URL.Query().Get("id")	case http.MethodGet:	switch r.Method {func (a *NotionAdapter) HandleDatabases(w http.ResponseWriter, r *http.Request) {}	}		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	default:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.notionRequest(r.Context(), http.MethodPatch, "/pages/"+id, req, &result); err != nil {		var result notionPage		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req map[string]interface{}		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if id == "" {		id := r.URL.Query().Get("id")	case http.MethodPatch:		json.NewEncoder(w).Encode(result)		w.WriteHeader(http.StatusCreated)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.notionRequest(r.Context(), http.MethodPost, "/pages", req, &result); err != nil {		var result notionPage		}			return			http.Error(w, err.Error(), http.StatusBadRequest)		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {		var req map[string]interface{}	case http.MethodPost:		json.NewEncoder(w).Encode(result)		w.Header().Set("Content-Type", "application/json")		}			return			http.Error(w, err.Error(), http.StatusInternalServerError)		if err := a.notionRequest(r.Context(), http.MethodGet, "/pages/"+id, nil, &result); err != nil {		var result notionPage		}			return			http.Error(w, "id query parameter is required", http.StatusBadRequest)		if id == "" {		id := r.URL.Query().Get("id")	case http.MethodGet:	switch r.Method {func (a *NotionAdapter) HandlePages(w http.ResponseWriter, r *http.Request) {}	w.WriteHeader(http.StatusOK)	}		}			}				log.Printf("failed to publish task completed event: %v", err)			if err := a.bus.Publish(r.Context(), events.Event{Type: events.TaskCompleted, Payload: ep}); err != nil {			})				"source":  "notion",				"page_id": page["id"],			ep, _ := json.Marshal(map[string]interface{}{		if page, ok := payload["entity"].(map[string]interface{}); ok {	case "page_updated":		}			}				log.Printf("failed to publish task created event: %v", err)			if err := a.bus.Publish(r.Context(), events.Event{Type: events.TaskCreated, Payload: ep}); err != nil {			})				"source":  "notion",				"url":     page["url"],				"page_id": page["id"],			ep, _ := json.Marshal(map[string]interface{}{		if page, ok := payload["entity"].(map[string]interface{}); ok {	case "page_created":	switch eventType {	eventType, _ := payload["type"].(string)	}		return		http.Error(w, err.Error(), http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {	var payload map[string]interface{}	}		return		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (a *NotionAdapter) HandleWebhook(w http.ResponseWriter, r *http.Request) {// integration webhook — currently in beta; falls back to polling pattern).// HandleWebhook processes Notion webhook events (requires Notion's internal}	http.ListenAndServe(":8126", mux)	log.Printf("Notion adapter listening on :8126")	mux.HandleFunc("/api/v1/databases", adapter.HandleDatabases)	mux.HandleFunc("/api/v1/pages", adapter.HandlePages)	mux.HandleFunc("/webhook", adapter.HandleWebhook)	})		w.WriteHeader(http.StatusOK)	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	mux := http.NewServeMux()	go adapter.subscribeToEvents()	}		httpClient:     &http.Client{},		bus:            bus,		forgeLabelProp: os.Getenv("NOTION_FORGE_LABEL_PROP"),		databaseID:     os.Getenv("NOTION_DATABASE_ID"),		token:          token,	adapter := &NotionAdapter{	}		log.Fatalf("failed to create event bus: %v", err)	if err != nil {	bus, err := events.NewRedisBus(os.Getenv("REDIS_ADDR"), "forge:events")	}		log.Fatal("NOTION_API_TOKEN is required")	if token == "" {	token := os.Getenv("NOTION_API_TOKEN")func main() {}	Properties map[string]interface{} `json:"properties"`	URL        string `json:"url"`	ID         string `json:"id"`type notionPage struct {}	httpClient    *http.Client	bus           events.Bus	forgeLabelProp string	databaseID    string	token         stringtype NotionAdapter struct {